// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretGcp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretGcp) DeepCopy() *DynamicSecretGcp {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretGcp)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretGcp) DeepCopyInto(out *DynamicSecretGcp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretGcpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretGcpList) DeepCopy() *DynamicSecretGcpList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretGcpList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretGcpList) DeepCopyInto(out *DynamicSecretGcpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretGcp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
