// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *Role) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RoleList) DeepCopy() *RoleList {
	if in == nil {
		return nil
	}
	out := new(RoleList)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleList) DeepCopyInto(out *RoleList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Role, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
