// Code generated by iac-forge. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	apis "github.com/pleme-io/crossplane-akeyless/apis"
	"github.com/pleme-io/crossplane-akeyless/internal/controller"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

func main() {
	leaderElection := false
	pollInterval := time.Minute
	flag.BoolVar(&leaderElection, "leader-election", false, "Enable leader election for the controller manager.")
	flag.DurationVar(&pollInterval, "poll", pollInterval, "Poll interval for managed-resource reconciliation.")
	flag.Parse()

	ctrl.SetLogger(zap.New(zap.UseDevMode(true)))

	cfg, err := ctrl.GetConfig()
	if err != nil {
		fmt.Fprintln(os.Stderr, "GetConfig:", err)
		os.Exit(1)
	}
	mgr, err := ctrl.NewManager(cfg, ctrl.Options{
		LeaderElection:   leaderElection,
		LeaderElectionID: "crossplane-akeyless-leader",
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "NewManager:", err)
		os.Exit(1)
	}

	if err := apis.AddToScheme(mgr.GetScheme()); err != nil {
		fmt.Fprintln(os.Stderr, "AddToScheme:", err)
		os.Exit(1)
	}
	if err := controller.Setup(mgr, pollInterval); err != nil {
		fmt.Fprintln(os.Stderr, "controller.Setup:", err)
		os.Exit(1)
	}
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		fmt.Fprintln(os.Stderr, "mgr.Start:", err)
		os.Exit(1)
	}
}
