// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetDockerhubParameters defines the desired state of the resource.
type TargetDockerhubParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Docker Hub password or access token
	// +optional
	DockerhubPassword *string `json:"dockerhub_password,omitempty"`
	// Docker Hub username
	// +optional
	DockerhubUsername *string `json:"dockerhub_username,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
}

// TargetDockerhubObservation reflects the observed state from the upstream provider.
type TargetDockerhubObservation struct {
}

// TargetDockerhubSpec is the desired state of the resource.
type TargetDockerhubSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetDockerhubParameters `json:"forProvider"`
}

// TargetDockerhubStatus reflects the observed state of the resource.
type TargetDockerhubStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetDockerhubObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetDockerhub struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetDockerhubSpec   `json:"spec"`
	Status            TargetDockerhubStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetDockerhubList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetDockerhub `json:"items"`
}
