// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetDockerhub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetDockerhub) DeepCopy() *TargetDockerhub {
	if in == nil {
		return nil
	}
	out := new(TargetDockerhub)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetDockerhub) DeepCopyInto(out *TargetDockerhub) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetDockerhubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetDockerhubList) DeepCopy() *TargetDockerhubList {
	if in == nil {
		return nil
	}
	out := new(TargetDockerhubList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetDockerhubList) DeepCopyInto(out *TargetDockerhubList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetDockerhub, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
