// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PkiCertIssuerParameters defines the desired state of the resource.
type PkiCertIssuerParameters struct {
	// If set, clients can request certificates for any CN
	// +optional
	AllowAnyName *bool `json:"allow_any_name,omitempty"`
	// Allow copying extra extensions from CSR
	// +optional
	AllowCopyExtFromCsr *bool `json:"allow_copy_ext_from_csr,omitempty"`
	// Allow certificates for subdomains of allowed domains
	// +optional
	AllowSubdomains *bool `json:"allow_subdomains,omitempty"`
	// Comma-delimited list of allowed domains
	// +optional
	AllowedDomains *string `json:"allowed_domains,omitempty"`
	// JSON string of allowed extra extensions
	// +optional
	AllowedExtraExtensions *string `json:"allowed_extra_extensions,omitempty"`
	// Comma-delimited list of allowed CIDRs for IP SANs
	// +optional
	AllowedIpSans *string `json:"allowed_ip_sans,omitempty"`
	// Comma-delimited list of allowed URIs for URI SANs
	// +optional
	AllowedUriSans *string `json:"allowed_uri_sans,omitempty"`
	// Automatically renew certificates before expiration
	// +optional
	AutoRenew *bool `json:"auto_renew,omitempty"`
	// Defines the X.509 Basic Constraints extension for certificates issued by this PKI issuer template
	// +optional
	BasicConstraints *string `json:"basic_constraints,omitempty"`
	// Name of existing CA target (required in Public CA mode)
	// +optional
	CaTarget *string `json:"ca_target,omitempty"`
	// Flag certificates for client auth use
	// +optional
	ClientFlag *bool `json:"client_flag,omitempty"`
	// Flag certificates for code signing use
	// +optional
	CodeSigningFlag *bool `json:"code_signing_flag,omitempty"`
	// Comma-separated list of countries for issued certificate
	// +optional
	Country *string `json:"country,omitempty"`
	// Expose CRL endpoint in Gateway
	// +optional
	CreatePrivateCrl *bool `json:"create_private_crl,omitempty"`
	// Expose private OCSP endpoint
	// +optional
	CreatePrivateOcsp *bool `json:"create_private_ocsp,omitempty"`
	// Expose public CRL endpoint
	// +optional
	CreatePublicCrl *bool `json:"create_public_crl,omitempty"`
	// Expose public OCSP endpoint
	// +optional
	CreatePublicOcsp *bool `json:"create_public_ocsp,omitempty"`
	// Mark key usage as critical
	// +optional
	CriticalKeyUsage *string `json:"critical_key_usage,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Destination path for generated certificates
	// +optional
	DestinationPath *string `json:"destination_path,omitempty"`
	// Disable wildcard certificates
	// +optional
	DisableWildcards *bool `json:"disable_wildcards,omitempty"`
	// Enable ACME protocol
	// +optional
	EnableAcme *bool `json:"enable_acme,omitempty"`
	// How many days before the expiration of the certificate would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Gateway cluster URL
	// +optional
	GwClusterUrl *string `json:"gw_cluster_url,omitempty"`
	// If set, the basic constraints is-ca flag is set
	// +optional
	IsCa *bool `json:"is_ca,omitempty"`
	// Key usage: DigitalSignature, KeyAgreement, KeyEncipherment
	// +optional
	KeyUsage *string `json:"key_usage,omitempty"`
	// Locality for issued certificate
	// +optional
	Locality *string `json:"locality,omitempty"`
	// Maximum path length for CA certificates
	// +optional
	MaxPathLen *int64 `json:"max_path_len,omitempty"`
	// PKI certificate issuer name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Do not enforce hostnames
	// +optional
	NotEnforceHostnames *bool `json:"not_enforce_hostnames,omitempty"`
	// Do not require common name
	// +optional
	NotRequireCn *bool `json:"not_require_cn,omitempty"`
	// OCSP response TTL
	// +optional
	OcspTtl *string `json:"ocsp_ttl,omitempty"`
	// Organizational units for issued certificate
	// +optional
	OrganizationalUnits *string `json:"organizational_units,omitempty"`
	// Organization for issued certificate
	// +optional
	Organizations *string `json:"organizations,omitempty"`
	// Postal code for issued certificate
	// +optional
	PostalCode *string `json:"postal_code,omitempty"`
	// Protect generated certificates
	// +optional
	ProtectCertificates *bool `json:"protect_certificates,omitempty"`
	// Province for issued certificate
	// +optional
	Province *string `json:"province,omitempty"`
	// Number of days before expiration to renew certificates
	// +optional
	ScheduledRenew *int64 `json:"scheduled_renew,omitempty"`
	// Flag certificates for server auth use
	// +optional
	ServerFlag *bool `json:"server_flag,omitempty"`
	// Key to sign certificates with
	// +optional
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	SignerKeyName *string `json:"signer_key_name,omitempty"`
	// Street address for issued certificate
	// +optional
	StreetAddress *string `json:"street_address,omitempty"`
	// Tags for the PKI cert issuer
	// +optional
	Tag *string `json:"tag,omitempty"`
	// Certificate TTL
	// +kubebuilder:validation:Required
	Ttl string `json:"ttl"`
}

// PkiCertIssuerObservation reflects the observed state from the upstream provider.
type PkiCertIssuerObservation struct {
}

// PkiCertIssuerSpec is the desired state of the resource.
type PkiCertIssuerSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       PkiCertIssuerParameters `json:"forProvider"`
}

// PkiCertIssuerStatus reflects the observed state of the resource.
type PkiCertIssuerStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          PkiCertIssuerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type PkiCertIssuer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PkiCertIssuerSpec   `json:"spec"`
	Status            PkiCertIssuerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type PkiCertIssuerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PkiCertIssuer `json:"items"`
}
