// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *PkiCertIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PkiCertIssuer) DeepCopy() *PkiCertIssuer {
	if in == nil {
		return nil
	}
	out := new(PkiCertIssuer)
	in.DeepCopyInto(out)
	return out
}

func (in *PkiCertIssuer) DeepCopyInto(out *PkiCertIssuer) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *PkiCertIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PkiCertIssuerList) DeepCopy() *PkiCertIssuerList {
	if in == nil {
		return nil
	}
	out := new(PkiCertIssuerList)
	in.DeepCopyInto(out)
	return out
}

func (in *PkiCertIssuerList) DeepCopyInto(out *PkiCertIssuerList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PkiCertIssuer, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
