// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RoleAuthMethodAssocParameters defines the desired state of the resource.
type RoleAuthMethodAssocParameters struct {
	// Auth method name to associate with the role
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	AmName string `json:"am_name"`
	// Case-sensitive sub-claims matching
	// +optional
	CaseSensitive *string `json:"case_sensitive,omitempty"`
	// Role name to associate
	// +kubebuilder:validation:Required
	RoleName string `json:"role_name"`
	// Sub-claims for the association (key=value pairs)
	// +optional
	SubClaims *string `json:"sub_claims,omitempty"`
}

// RoleAuthMethodAssocObservation reflects the observed state from the upstream provider.
type RoleAuthMethodAssocObservation struct {
}

// RoleAuthMethodAssocSpec is the desired state of the resource.
type RoleAuthMethodAssocSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       RoleAuthMethodAssocParameters `json:"forProvider"`
}

// RoleAuthMethodAssocStatus reflects the observed state of the resource.
type RoleAuthMethodAssocStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          RoleAuthMethodAssocObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type RoleAuthMethodAssoc struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RoleAuthMethodAssocSpec   `json:"spec"`
	Status            RoleAuthMethodAssocStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type RoleAuthMethodAssocList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleAuthMethodAssoc `json:"items"`
}
