// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretLdap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretLdap) DeepCopy() *RotatedSecretLdap {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretLdap)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretLdap) DeepCopyInto(out *RotatedSecretLdap) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretLdapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretLdapList) DeepCopy() *RotatedSecretLdapList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretLdapList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretLdapList) DeepCopyInto(out *RotatedSecretLdapList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretLdap, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
