// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerK8sParameters defines the desired state of the resource.
type GatewayProducerK8sParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Comma-separated list of allowed K8S namespaces for the generated ServiceAccount (relevant only for k8s-service-account-type=dynamic)
	// +optional
	K8sAllowedNamespaces *string `json:"k8s_allowed_namespaces,omitempty"`
	// K8S cluster CA certificate
	// +optional
	K8sClusterCaCert *string `json:"k8s_cluster_ca_cert,omitempty"`
	// K8S cluster URL endpoint
	// +optional
	K8sClusterEndpoint *string `json:"k8s_cluster_endpoint,omitempty"`
	// K8S cluster name
	// +optional
	K8sClusterName *string `json:"k8s_cluster_name,omitempty"`
	// K8S cluster Bearer token
	// +optional
	K8sClusterToken *string `json:"k8s_cluster_token,omitempty"`
	// K8S Namespace where the ServiceAccount exists.
	// +optional
	K8sNamespace *string `json:"k8s_namespace,omitempty"`
	// The pre-existing Role or ClusterRole name to bind the generated ServiceAccount to (relevant only for k8s-service-account-type=dynamic)
	// +optional
	K8sPredefinedRoleName *string `json:"k8s_predefined_role_name,omitempty"`
	// Specifies the type of the pre-existing K8S role [Role, ClusterRole] (relevant only for k8s-service-account-type=dynamic)
	// +optional
	K8sPredefinedRoleType *string `json:"k8s_predefined_role_type,omitempty"`
	// Content of the yaml in a Base64 format.
	// +optional
	K8sRolebindingYamlData *string `json:"k8s_rolebinding_yaml_data,omitempty"`
	// Path to yaml file that contains definitions of K8S role and role binding (relevant only for k8s-service-account-type=dynamic)
	// +optional
	K8sRolebindingYamlDef *string `json:"k8s_rolebinding_yaml_def,omitempty"`
	// K8S ServiceAccount to extract token from.
	// +optional
	K8sServiceAccount *string `json:"k8s_service_account,omitempty"`
	// K8S ServiceAccount type [fixed, dynamic].
	// +optional
	K8sServiceAccountType *string `json:"k8s_service_account_type,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Enable Port forwarding while using CLI access
	// +optional
	SecureAccessAllowPortForwading *bool `json:"secure_access_allow_port_forwading,omitempty"`
	// The K8s cluster endpoint URL
	// +optional
	SecureAccessClusterEndpoint *string `json:"secure_access_cluster_endpoint,omitempty"`
	// The K8s dashboard url
	// +optional
	SecureAccessDashboardUrl *string `json:"secure_access_dashboard_url,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Use the GW's service account
	// +optional
	UseGwServiceAccount *bool `json:"use_gw_service_account,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerK8sObservation reflects the observed state from the upstream provider.
type GatewayProducerK8sObservation struct {
}

// GatewayProducerK8sSpec is the desired state of the resource.
type GatewayProducerK8sSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerK8sParameters `json:"forProvider"`
}

// GatewayProducerK8sStatus reflects the observed state of the resource.
type GatewayProducerK8sStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerK8sObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerK8s struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerK8sSpec   `json:"spec"`
	Status            GatewayProducerK8sStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerK8sList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerK8s `json:"items"`
}
