// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretWindows) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretWindows) DeepCopy() *RotatedSecretWindows {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretWindows)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretWindows) DeepCopyInto(out *RotatedSecretWindows) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretWindowsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretWindowsList) DeepCopy() *RotatedSecretWindowsList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretWindowsList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretWindowsList) DeepCopyInto(out *RotatedSecretWindowsList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretWindows, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
