// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodKerberosParameters defines the desired state of the resource.
type AuthMethodKerberosParameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// +optional
	BindDn *string `json:"bind_dn,omitempty"`
	// +optional
	BindDnPassword *string `json:"bind_dn_password,omitempty"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// +optional
	GroupAttr *string `json:"group_attr,omitempty"`
	// +optional
	GroupDn *string `json:"group_dn,omitempty"`
	// +optional
	GroupFilter *string `json:"group_filter,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Kerberos keytab file data (base64)
	// +optional
	KeytabFileData *string `json:"keytab_file_data,omitempty"`
	// Path to Kerberos keytab file on gateway
	// +optional
	KeytabFilePath *string `json:"keytab_file_path,omitempty"`
	// Kerberos krb5.conf file data (base64)
	// +optional
	Krb5ConfData *string `json:"krb5_conf_data,omitempty"`
	// Path to krb5.conf file on gateway
	// +optional
	Krb5ConfPath *string `json:"krb5_conf_path,omitempty"`
	// +optional
	LdapAnonymousSearch *bool `json:"ldap_anonymous_search,omitempty"`
	// +optional
	LdapCaCert *string `json:"ldap_ca_cert,omitempty"`
	// +optional
	LdapUrl *string `json:"ldap_url,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
	// A list of additional sub claims delimiters (relevant only for SAML, OIDC, OAuth2/JWT)
	// +optional
	SubclaimsDelimiters *string `json:"subclaims_delimiters,omitempty"`
	// A unique identifier (ID) value which is a "sub claim" name that contains details uniquely identifying that resource. This "sub claim" is used to distinguish between different identities.
	// +optional
	UniqueIdentifier *string `json:"unique_identifier,omitempty"`
	// +optional
	UserAttribute *string `json:"user_attribute,omitempty"`
	// +optional
	UserDn *string `json:"user_dn,omitempty"`
}

// AuthMethodKerberosObservation reflects the observed state from the upstream provider.
type AuthMethodKerberosObservation struct {
}

// AuthMethodKerberosSpec is the desired state of the resource.
type AuthMethodKerberosSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodKerberosParameters `json:"forProvider"`
}

// AuthMethodKerberosStatus reflects the observed state of the resource.
type AuthMethodKerberosStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodKerberosObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodKerberos struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodKerberosSpec   `json:"spec"`
	Status            AuthMethodKerberosStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodKerberosList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodKerberos `json:"items"`
}
