// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretGoogleWorkspaceParameters defines the desired state of the resource.
type DynamicSecretGoogleWorkspaceParameters struct {
	// +kubebuilder:validation:Required
	AccessMode string `json:"access_mode"`
	// Admin user email
	// +kubebuilder:validation:Required
	AdminEmail string `json:"admin_email"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// For externally provided users, denotes the key-name of IdP claim to extract the username from
	// +optional
	FixedUserClaimKeyname *string `json:"fixed_user_claim_keyname,omitempty"`
	// Base64-encoded service account private key text
	// +optional
	GcpKey *string `json:"gcp_key,omitempty"`
	// A group email, relevant only for group access-mode
	// +optional
	GroupEmail *string `json:"group_email,omitempty"`
	// +optional
	GroupRole *string `json:"group_role,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Google Workspace admin role
	// +optional
	RoleName *string `json:"role_name,omitempty"`
	// Google Workspace role scope (ORG_UNIT)
	// +optional
	RoleScope *string `json:"role_scope,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretGoogleWorkspaceObservation reflects the observed state from the upstream provider.
type DynamicSecretGoogleWorkspaceObservation struct {
}

// DynamicSecretGoogleWorkspaceSpec is the desired state of the resource.
type DynamicSecretGoogleWorkspaceSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretGoogleWorkspaceParameters `json:"forProvider"`
}

// DynamicSecretGoogleWorkspaceStatus reflects the observed state of the resource.
type DynamicSecretGoogleWorkspaceStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretGoogleWorkspaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretGoogleWorkspace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretGoogleWorkspaceSpec   `json:"spec"`
	Status            DynamicSecretGoogleWorkspaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretGoogleWorkspaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretGoogleWorkspace `json:"items"`
}
