// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *EventForwarderSlack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderSlack) DeepCopy() *EventForwarderSlack {
	if in == nil {
		return nil
	}
	out := new(EventForwarderSlack)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderSlack) DeepCopyInto(out *EventForwarderSlack) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *EventForwarderSlackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderSlackList) DeepCopy() *EventForwarderSlackList {
	if in == nil {
		return nil
	}
	out := new(EventForwarderSlackList)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderSlackList) DeepCopyInto(out *EventForwarderSlackList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EventForwarderSlack, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
