// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerCassandraParameters defines the desired state of the resource.
type GatewayProducerCassandraParameters struct {
	// Cassandra creation statements
	// +optional
	CassandraCreationStatements *string `json:"cassandra_creation_statements,omitempty"`
	// Cassandra hosts IP or addresses, comma separated
	// +optional
	CassandraHosts *string `json:"cassandra_hosts,omitempty"`
	// Cassandra superuser password
	// +optional
	CassandraPassword *string `json:"cassandra_password,omitempty"`
	// Cassandra port
	// +optional
	CassandraPort *string `json:"cassandra_port,omitempty"`
	// Cassandra superuser username
	// +optional
	CassandraUsername *string `json:"cassandra_username,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Enable/Disable SSL [true/false]
	// +optional
	Ssl *bool `json:"ssl,omitempty"`
	// SSL CA certificate in base64 encoding generated from a trusted Certificate Authority (CA)
	// +optional
	SslCertificate *string `json:"ssl_certificate,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerCassandraObservation reflects the observed state from the upstream provider.
type GatewayProducerCassandraObservation struct {
}

// GatewayProducerCassandraSpec is the desired state of the resource.
type GatewayProducerCassandraSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerCassandraParameters `json:"forProvider"`
}

// GatewayProducerCassandraStatus reflects the observed state of the resource.
type GatewayProducerCassandraStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerCassandraObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerCassandra struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerCassandraSpec   `json:"spec"`
	Status            GatewayProducerCassandraStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerCassandraList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerCassandra `json:"items"`
}
