// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerCassandra) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerCassandra) DeepCopy() *GatewayProducerCassandra {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerCassandra)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerCassandra) DeepCopyInto(out *GatewayProducerCassandra) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerCassandraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerCassandraList) DeepCopy() *GatewayProducerCassandraList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerCassandraList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerCassandraList) DeepCopyInto(out *GatewayProducerCassandraList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerCassandra, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
