// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *KmipClientV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KmipClientV2) DeepCopy() *KmipClientV2 {
	if in == nil {
		return nil
	}
	out := new(KmipClientV2)
	in.DeepCopyInto(out)
	return out
}

func (in *KmipClientV2) DeepCopyInto(out *KmipClientV2) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *KmipClientV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KmipClientV2List) DeepCopy() *KmipClientV2List {
	if in == nil {
		return nil
	}
	out := new(KmipClientV2List)
	in.DeepCopyInto(out)
	return out
}

func (in *KmipClientV2List) DeepCopyInto(out *KmipClientV2List) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KmipClientV2, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
