// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretDockerhub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretDockerhub) DeepCopy() *RotatedSecretDockerhub {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretDockerhub)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretDockerhub) DeepCopyInto(out *RotatedSecretDockerhub) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretDockerhubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretDockerhubList) DeepCopy() *RotatedSecretDockerhubList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretDockerhubList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretDockerhubList) DeepCopyInto(out *RotatedSecretDockerhubList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretDockerhub, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
