// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetK8sParameters defines the desired state of the resource.
type TargetK8sParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Kubernetes auth type: token, certificate, or password
	// +optional
	K8sAuthType *string `json:"k8s_auth_type,omitempty"`
	// Kubernetes client certificate (PEM)
	// +optional
	K8sClientCertificate *string `json:"k8s_client_certificate,omitempty"`
	// Kubernetes client key (PEM)
	// +optional
	K8sClientKey *string `json:"k8s_client_key,omitempty"`
	// Kubernetes cluster CA certificate (PEM)
	// +optional
	K8sClusterCaCert *string `json:"k8s_cluster_ca_cert,omitempty"`
	// Kubernetes API server URL
	// +optional
	K8sClusterEndpoint *string `json:"k8s_cluster_endpoint,omitempty"`
	// K8S cluster name
	// +optional
	K8sClusterName *string `json:"k8s_cluster_name,omitempty"`
	// Kubernetes bearer token
	// +optional
	K8sClusterToken *string `json:"k8s_cluster_token,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Use gateway service account for authentication
	// +optional
	UseGwServiceAccount *bool `json:"use_gw_service_account,omitempty"`
}

// TargetK8sObservation reflects the observed state from the upstream provider.
type TargetK8sObservation struct {
}

// TargetK8sSpec is the desired state of the resource.
type TargetK8sSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetK8sParameters `json:"forProvider"`
}

// TargetK8sStatus reflects the observed state of the resource.
type TargetK8sStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetK8sObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetK8s struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetK8sSpec   `json:"spec"`
	Status            TargetK8sStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetK8sList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetK8s `json:"items"`
}
