// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetK8s) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetK8s) DeepCopy() *TargetK8s {
	if in == nil {
		return nil
	}
	out := new(TargetK8s)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetK8s) DeepCopyInto(out *TargetK8s) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetK8sList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetK8sList) DeepCopy() *TargetK8sList {
	if in == nil {
		return nil
	}
	out := new(TargetK8sList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetK8sList) DeepCopyInto(out *TargetK8sList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetK8s, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
