// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerPostgresql) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerPostgresql) DeepCopy() *GatewayProducerPostgresql {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerPostgresql)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerPostgresql) DeepCopyInto(out *GatewayProducerPostgresql) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerPostgresqlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerPostgresqlList) DeepCopy() *GatewayProducerPostgresqlList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerPostgresqlList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerPostgresqlList) DeepCopyInto(out *GatewayProducerPostgresqlList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerPostgresql, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
