apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: folders.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: Folder
    plural: folders
    singular: folder
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  accessibility:
                    description: 'Folder accessibility: regular or personal'
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the folder
                    type: string
                  name:
                    description: Folder name (immutable)
                    type: string
                  tags:
                    description: Tags for the folder
                    items:
                      type: string
                    type: array
                  type:
                    type: string
                required:
                - name
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  accessibility:
                    description: 'Folder accessibility: regular or personal'
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the folder
                    type: string
                  name:
                    description: Folder name
                    type: string
                  tags:
                    description: Tags for the folder
                    items:
                      type: string
                    type: array
                  type:
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
