apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dynamicsecretvenafis.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: DynamicSecretVenafi
    plural: dynamicsecretvenafis
    singular: dynamicsecretvenafi
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  admin_rotation_interval_days:
                    description: Admin credentials rotation interval (days)
                    format: int64
                    type: integer
                  allow_subdomains:
                    description: Allow subdomains
                    type: boolean
                  allowed_domains:
                    description: Allowed domains
                    items:
                      type: string
                    type: array
                  auto_generated_folder:
                    description: Auto generated folder
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the object
                    type: string
                  enable_admin_rotation:
                    description: Automatic admin credentials rotation
                    type: boolean
                  item_custom_fields:
                    additionalProperties:
                      type: string
                    description: Additional custom fields to associate with the item
                    type: object
                  name:
                    description: Dynamic secret name (immutable)
                    type: string
                  producer_encryption_key_name:
                    description: Dynamic producer encryption key
                    type: string
                  root_first_in_chain:
                    description: Root first in chain
                    type: boolean
                  sign_using_akeyless_pki:
                    description: Use Akeyless PKI issuer or Venafi issuer
                    type: boolean
                  signer_key_name:
                    description: Signer key name
                    type: string
                  store_private_key:
                    description: Store private key in Akeyless
                    type: boolean
                  tags:
                    description: Tags for the producer
                    items:
                      type: string
                    type: array
                  target_name:
                    description: Target name associated with this producer
                    type: string
                  user_ttl:
                    description: User TTL (e.g., 60m, 12h)
                    type: string
                  venafi_access_token:
                    description: Venafi Access Token to use to access the TPP environment (Relevant when using TPP)
                    type: string
                  venafi_api_key:
                    description: Venafi API key [sensitive]
                    type: string
                  venafi_baseurl:
                    description: Venafi base URL
                    type: string
                  venafi_client_id:
                    description: Venafi Client ID that was used when the access token was generated
                    type: string
                  venafi_refresh_token:
                    description: Venafi Refresh Token to use when the Access Token is expired (Relevant when using TPP)
                    type: string
                  venafi_use_tpp:
                    description: Use Venafi TPP (instead of Cloud)
                    type: boolean
                  venafi_zone:
                    description: Venafi zone/policy folder
                    type: string
                required:
                - name
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  admin_rotation_interval_days:
                    description: Admin credentials rotation interval (days)
                    format: int64
                    type: integer
                  allow_subdomains:
                    description: Allow subdomains
                    type: boolean
                  allowed_domains:
                    description: Allowed domains
                    items:
                      type: string
                    type: array
                  auto_generated_folder:
                    description: Auto generated folder
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the object
                    type: string
                  enable_admin_rotation:
                    description: Automatic admin credentials rotation
                    type: boolean
                  item_custom_fields:
                    additionalProperties:
                      type: string
                    description: Additional custom fields to associate with the item
                    type: object
                  name:
                    description: Dynamic secret name
                    type: string
                  producer_encryption_key_name:
                    description: Dynamic producer encryption key
                    type: string
                  root_first_in_chain:
                    description: Root first in chain
                    type: boolean
                  sign_using_akeyless_pki:
                    description: Use Akeyless PKI issuer or Venafi issuer
                    type: boolean
                  signer_key_name:
                    description: Signer key name
                    type: string
                  store_private_key:
                    description: Store private key in Akeyless
                    type: boolean
                  tags:
                    description: Tags for the producer
                    items:
                      type: string
                    type: array
                  target_name:
                    description: Target name associated with this producer
                    type: string
                  user_ttl:
                    description: User TTL (e.g., 60m, 12h)
                    type: string
                  venafi_access_token:
                    description: Venafi Access Token to use to access the TPP environment (Relevant when using TPP)
                    type: string
                  venafi_api_key:
                    description: Venafi API key
                    type: string
                  venafi_baseurl:
                    description: Venafi base URL
                    type: string
                  venafi_client_id:
                    description: Venafi Client ID that was used when the access token was generated
                    type: string
                  venafi_refresh_token:
                    description: Venafi Refresh Token to use when the Access Token is expired (Relevant when using TPP)
                    type: string
                  venafi_use_tpp:
                    description: Use Venafi TPP (instead of Cloud)
                    type: boolean
                  venafi_zone:
                    description: Venafi zone/policy folder
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
