apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dynamicsecretrediss.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: DynamicSecretRedis
    plural: dynamicsecretrediss
    singular: dynamicsecretredis
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  acl_rules:
                    description: |-
                      A JSON array list of redis ACL rules to attach to the created user. For available rules see the ACL CAT command https://redis.io/commands/acl-cat
                      By default the user will have permissions to read all keys '["~*", "+@read"]'
                    type: string
                  custom_username_template:
                    description: Customize how temporary usernames are generated using go template
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the object
                    type: string
                  host:
                    description: Redis host
                    type: string
                  item_custom_fields:
                    additionalProperties:
                      type: string
                    description: Additional custom fields to associate with the item
                    type: object
                  name:
                    description: Dynamic secret name (immutable)
                    type: string
                  password_length:
                    description: The length of the password to be generated
                    type: string
                  port:
                    description: 'Redis port (default: 6379)'
                    type: string
                  producer_encryption_key_name:
                    description: Dynamic producer encryption key
                    type: string
                  ssl:
                    description: Enable SSL connection
                    type: boolean
                  ssl_certificate:
                    description: SSL certificate (PEM) [sensitive]
                    type: string
                  tags:
                    description: Tags for the producer
                    items:
                      type: string
                    type: array
                  target_name:
                    description: Target name associated with this producer
                    type: string
                  user_ttl:
                    description: User TTL (e.g., 60m, 12h)
                    type: string
                required:
                - name
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  acl_rules:
                    description: |-
                      A JSON array list of redis ACL rules to attach to the created user. For available rules see the ACL CAT command https://redis.io/commands/acl-cat
                      By default the user will have permissions to read all keys '["~*", "+@read"]'
                    type: string
                  custom_username_template:
                    description: Customize how temporary usernames are generated using go template
                    type: string
                  delete_protection:
                    description: Enable delete protection
                    type: boolean
                  description:
                    description: Description of the object
                    type: string
                  host:
                    description: Redis host
                    type: string
                  item_custom_fields:
                    additionalProperties:
                      type: string
                    description: Additional custom fields to associate with the item
                    type: object
                  name:
                    description: Dynamic secret name
                    type: string
                  password_length:
                    description: The length of the password to be generated
                    type: string
                  port:
                    description: 'Redis port (default: 6379)'
                    type: string
                  producer_encryption_key_name:
                    description: Dynamic producer encryption key
                    type: string
                  ssl:
                    description: Enable SSL connection
                    type: boolean
                  ssl_certificate:
                    description: SSL certificate (PEM)
                    type: string
                  tags:
                    description: Tags for the producer
                    items:
                      type: string
                    type: array
                  target_name:
                    description: Target name associated with this producer
                    type: string
                  user_ttl:
                    description: User TTL (e.g., 60m, 12h)
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
