apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventforwarderservicenows.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: EventForwarderServicenow
    plural: eventforwarderservicenows
    singular: eventforwarderservicenow
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  admin_name:
                    description: Workstation Admin Name
                    type: string
                  admin_pwd:
                    description: Workstation Admin Password
                    type: string
                  app_private_key_base64:
                    description: The RSA Private Key to use when connecting with jwt authentication
                    type: string
                  auth_methods_event_source_locations:
                    description: Auth Method Event sources
                    items:
                      type: string
                    type: array
                  auth_type:
                    description: The authentication type to use [user-pass/jwt]
                    type: string
                  client_id:
                    description: The client ID to use when connecting with jwt authentication
                    type: string
                  client_secret:
                    description: The client secret to use when connecting with jwt authentication
                    type: string
                  description:
                    description: Description of the object
                    type: string
                  event_types:
                    description: List of event types to notify about [request-access, certificate-pending-expiration, certificate-expired, certificate-provisioning-success, certificate-provisioning-failure, auth-method-pending-expiration, auth-method-expired, next-automatic-rotation, rotated-secret-success, rotated-secret-failure, dynamic-secret-failure, multi-auth-failure, uid-rotation-failure, apply-justification, email-auth-method-approved, usage, rotation-usage, gateway-inactive, static-secret-updated, rate-limiting, usage-report, secret-sync]
                    items:
                      type: string
                    type: array
                  every:
                    description: Rate of periodic runner repetition in hours
                    type: string
                  gateways_event_source_locations:
                    description: Event sources
                    items:
                      type: string
                    type: array
                  host:
                    description: Workstation Host
                    type: string
                  items_event_source_locations:
                    description: Items Event sources
                    items:
                      type: string
                    type: array
                  key:
                    description: The name of a key that used to encrypt the EventForwarder secret value (if empty, the account default protectionKey key will be used)
                    type: string
                  name:
                    description: EventForwarder name (immutable)
                    type: string
                  runner_type:
                    type: string
                  targets_event_source_locations:
                    description: Targets Event sources
                    items:
                      type: string
                    type: array
                  user_email:
                    description: The user email to identify with when connecting with jwt authentication
                    type: string
                required:
                - gateways_event_source_locations
                - name
                - runner_type
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  admin_name:
                    description: Workstation Admin Name
                    type: string
                  admin_pwd:
                    description: Workstation Admin Password
                    type: string
                  app_private_key_base64:
                    description: The RSA Private Key to use when connecting with jwt authentication
                    type: string
                  auth_methods_event_source_locations:
                    description: Auth Method Event sources
                    items:
                      type: string
                    type: array
                  auth_type:
                    description: The authentication type to use [user-pass/jwt]
                    type: string
                  client_id:
                    description: The client ID to use when connecting with jwt authentication
                    type: string
                  client_secret:
                    description: The client secret to use when connecting with jwt authentication
                    type: string
                  description:
                    description: Description of the object
                    type: string
                  event_types:
                    description: List of event types to notify about [request-access, certificate-pending-expiration, certificate-expired, certificate-provisioning-success, certificate-provisioning-failure, auth-method-pending-expiration, auth-method-expired, next-automatic-rotation, rotated-secret-success, rotated-secret-failure, dynamic-secret-failure, multi-auth-failure, uid-rotation-failure, apply-justification, email-auth-method-approved, usage, rotation-usage, gateway-inactive, static-secret-updated, rate-limiting, usage-report, secret-sync]
                    items:
                      type: string
                    type: array
                  every:
                    description: Rate of periodic runner repetition in hours
                    type: string
                  gateways_event_source_locations:
                    description: Event sources
                    items:
                      type: string
                    type: array
                  host:
                    description: Workstation Host
                    type: string
                  items_event_source_locations:
                    description: Items Event sources
                    items:
                      type: string
                    type: array
                  key:
                    description: The name of a key that used to encrypt the EventForwarder secret value (if empty, the account default protectionKey key will be used)
                    type: string
                  name:
                    description: EventForwarder name
                    type: string
                  runner_type:
                    type: string
                  targets_event_source_locations:
                    description: Targets Event sources
                    items:
                      type: string
                    type: array
                  user_email:
                    description: The user email to identify with when connecting with jwt authentication
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
