apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targetopenais.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: TargetOpenai
    plural: targetopenais
    singular: targetopenai
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  api_key:
                    description: API key for OpenAI
                    type: string
                  api_key_id:
                    description: API key ID
                    type: string
                  description:
                    description: Target description
                    type: string
                  key:
                    description: The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
                    type: string
                  max_versions:
                    description: Set the maximum number of versions, limited by the account settings defaults.
                    type: string
                  model:
                    description: Default model to use with OpenAI
                    type: string
                  name:
                    description: Target name (immutable)
                    type: string
                  openai_url:
                    description: Base URL of the OpenAI API
                    type: string
                  organization_id:
                    description: Organization ID
                    type: string
                required:
                - name
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  api_key:
                    description: API key for OpenAI
                    type: string
                  api_key_id:
                    description: API key ID
                    type: string
                  description:
                    description: Target description
                    type: string
                  key:
                    description: The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
                    type: string
                  max_versions:
                    description: Set the maximum number of versions, limited by the account settings defaults.
                    type: string
                  model:
                    description: Default model to use with OpenAI
                    type: string
                  name:
                    description: Target name
                    type: string
                  openai_url:
                    description: Base URL of the OpenAI API
                    type: string
                  organization_id:
                    description: Organization ID
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
