apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uscs.akeyless.crossplane.io
spec:
  group: akeyless.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - akeyless
    kind: Usc
    plural: uscs
    singular: usc
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              forProvider:
                properties:
                  binary_value:
                    description: Use this option if the universal secrets value is a base64 encoded binary
                    type: boolean
                  description:
                    description: Description of the universal secrets
                    type: string
                  namespace:
                    description: The namespace (relevant for Hashi vault target)
                    type: string
                  object_type:
                    type: string
                  pfx_password:
                    description: Optional, the passphrase that protects the private key within the pfx certificate (Relevant only for Azure KV certificates)
                    type: string
                  region:
                    description: |-
                      Optional, create secret in a specific region (GCP only).
                      If empty, a global secret will be created (provider default).
                    type: string
                  secret_name:
                    description: Name for the new universal secrets
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: Tags for the universal secrets
                    type: object
                  usc_encryption_key:
                    description: Optional, The name of the remote key that used to encrypt the secret value (if empty, the default key will be used)
                    type: string
                  usc_name:
                    description: Name of the Universal Secrets Connector item
                    type: string
                  value:
                    description: Value of the universal secrets item, either text or base64 encoded binary
                    type: string
                required:
                - secret_name
                - usc_name
                - value
                type: object
            required:
            - forProvider
            type: object
          status:
            properties:
              atProvider:
                properties:
                  binary_value:
                    description: Use this option if the universal secrets value is a base64 encoded binary
                    type: boolean
                  description:
                    description: Description of the universal secrets
                    type: string
                  namespace:
                    description: The namespace (relevant for Hashi vault target)
                    type: string
                  object_type:
                    type: string
                  pfx_password:
                    description: Optional, the passphrase that protects the private key within the pfx certificate (Relevant only for Azure KV certificates)
                    type: string
                  region:
                    description: |-
                      Optional, create secret in a specific region (GCP only).
                      If empty, a global secret will be created (provider default).
                    type: string
                  secret_name:
                    description: Name for the new universal secrets
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: Tags for the universal secrets
                    type: object
                  usc_encryption_key:
                    description: Optional, The name of the remote key that used to encrypt the secret value (if empty, the default key will be used)
                    type: string
                  usc_name:
                    description: Name of the Universal Secrets Connector item
                    type: string
                  value:
                    description: Value of the universal secrets item, either text or base64 encoded binary
                    type: string
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
