// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodUniversalIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodUniversalIdentity) DeepCopy() *AuthMethodUniversalIdentity {
	if in == nil {
		return nil
	}
	out := new(AuthMethodUniversalIdentity)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodUniversalIdentity) DeepCopyInto(out *AuthMethodUniversalIdentity) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodUniversalIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodUniversalIdentityList) DeepCopy() *AuthMethodUniversalIdentityList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodUniversalIdentityList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodUniversalIdentityList) DeepCopyInto(out *AuthMethodUniversalIdentityList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodUniversalIdentity, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
