// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *StaticSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticSecret) DeepCopy() *StaticSecret {
	if in == nil {
		return nil
	}
	out := new(StaticSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticSecret) DeepCopyInto(out *StaticSecret) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *StaticSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticSecretList) DeepCopy() *StaticSecretList {
	if in == nil {
		return nil
	}
	out := new(StaticSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticSecretList) DeepCopyInto(out *StaticSecretList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]StaticSecret, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
