// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetSshParameters defines the desired state of the resource.
type TargetSshParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// SSH host address
	// +optional
	Host *string `json:"host,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// SSH port (default: 22)
	// +optional
	Port *string `json:"port,omitempty"`
	// SSH private key (PEM)
	// +optional
	PrivateKey *string `json:"private_key,omitempty"`
	// SSH private key passphrase
	// +optional
	PrivateKeyPassword *string `json:"private_key_password,omitempty"`
	// SSH password
	// +optional
	SshPassword *string `json:"ssh_password,omitempty"`
	// SSH username
	// +optional
	SshUsername *string `json:"ssh_username,omitempty"`
}

// TargetSshObservation reflects the observed state from the upstream provider.
type TargetSshObservation struct {
}

// TargetSshSpec is the desired state of the resource.
type TargetSshSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetSshParameters `json:"forProvider"`
}

// TargetSshStatus reflects the observed state of the resource.
type TargetSshStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetSshObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetSsh struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetSshSpec   `json:"spec"`
	Status            TargetSshStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetSshList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetSsh `json:"items"`
}
