// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetSsh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSsh) DeepCopy() *TargetSsh {
	if in == nil {
		return nil
	}
	out := new(TargetSsh)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSsh) DeepCopyInto(out *TargetSsh) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetSshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSshList) DeepCopy() *TargetSshList {
	if in == nil {
		return nil
	}
	out := new(TargetSshList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSshList) DeepCopyInto(out *TargetSshList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetSsh, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
