// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetDbParameters defines the desired state of the resource.
type TargetDbParameters struct {
	// (Optional) Client id (relevant for "cloud-service-provider" only)
	// +optional
	AzureClientId *string `json:"azure_client_id,omitempty"`
	// (Optional) Client secret (relevant for "cloud-service-provider" only)
	// +optional
	AzureClientSecret *string `json:"azure_client_secret,omitempty"`
	// (Optional) Tenant id (relevant for "cloud-service-provider" only)
	// +optional
	AzureTenantId *string `json:"azure_tenant_id,omitempty"`
	// Client certificate for mutual TLS
	// +optional
	ClientCertificate *string `json:"client_certificate,omitempty"`
	// Client private key passphrase for mutual TLS
	// +optional
	ClientKeyPassphrase *string `json:"client_key_passphrase,omitempty"`
	// Client private key for mutual TLS
	// +optional
	ClientPrivateKey *string `json:"client_private_key,omitempty"`
	// (Optional) Cloud service provider (currently only supports Azure)
	// +optional
	CloudServiceProvider *string `json:"cloud_service_provider,omitempty"`
	// Cluster Mode
	// +optional
	ClusterMode *bool `json:"cluster_mode,omitempty"`
	// Deprecated - use description
	// +optional
	Comment *string `json:"comment,omitempty"`
	// Type of connection to mssql database [credentials/cloud-identity/wallet/parent-target]
	// +kubebuilder:validation:Required
	ConnectionType string `json:"connection_type"`
	// Database name
	// +optional
	DbName *string `json:"db_name,omitempty"`
	// Database server TLS certificates (PEM)
	// +optional
	DbServerCertificates *string `json:"db_server_certificates,omitempty"`
	// Database server name for TLS verification
	// +optional
	DbServerName *string `json:"db_server_name,omitempty"`
	// Database type: mysql, mssql, postgresql, mongodb, snowflake, oracle, cassandra, redshift, hanadb
	// +kubebuilder:validation:Required
	DbType string `json:"db_type"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Enable mutual TLS
	// +optional
	EnableMtls *bool `json:"enable_mtls,omitempty"`
	// Database hostname
	// +optional
	Host *string `json:"host,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Use MongoDB Atlas connection
	// +optional
	MongodbAtlas *bool `json:"mongodb_atlas,omitempty"`
	// MongoDB Atlas API private key
	// +optional
	MongodbAtlasApiPrivateKey *string `json:"mongodb_atlas_api_private_key,omitempty"`
	// MongoDB Atlas API public key
	// +optional
	MongodbAtlasApiPublicKey *string `json:"mongodb_atlas_api_public_key,omitempty"`
	// MongoDB Atlas project ID
	// +optional
	MongodbAtlasProjectId *string `json:"mongodb_atlas_project_id,omitempty"`
	// MongoDB default authentication database
	// +optional
	MongodbDefaultAuthDb *string `json:"mongodb_default_auth_db,omitempty"`
	// MongoDB additional URI options
	// +optional
	MongodbUriOptions *string `json:"mongodb_uri_options,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Oracle service name
	// +optional
	OracleServiceName *string `json:"oracle_service_name,omitempty"`
	// Oracle Wallet login type (password/mtls)
	// +optional
	OracleWalletLoginType *string `json:"oracle_wallet_login_type,omitempty"`
	// Oracle wallet p12 file data in base64
	// +optional
	OracleWalletP12FileData *string `json:"oracle_wallet_p12_file_data,omitempty"`
	// Oracle wallet sso file data in base64
	// +optional
	OracleWalletSsoFileData *string `json:"oracle_wallet_sso_file_data,omitempty"`
	// Name of the parent target, relevant only when connection-type is parent-target
	// +optional
	ParentTargetName *string `json:"parent_target_name,omitempty"`
	// Database port
	// +optional
	Port *string `json:"port,omitempty"`
	// Database password
	// +optional
	Pwd *string `json:"pwd,omitempty"`
	// Snowflake account identifier
	// +optional
	SnowflakeAccount *string `json:"snowflake_account,omitempty"`
	// RSA Private key (base64 encoded)
	// +optional
	SnowflakeApiPrivateKey *string `json:"snowflake_api_private_key,omitempty"`
	// The Private key passphrase
	// +optional
	SnowflakeApiPrivateKeyPassword *string `json:"snowflake_api_private_key_password,omitempty"`
	// Enable SSL connection
	// +optional
	Ssl *bool `json:"ssl,omitempty"`
	// Client SSL certificate (PEM)
	// +optional
	SslCertificate *string `json:"ssl_certificate,omitempty"`
	// Database username
	// +optional
	UserName *string `json:"user_name,omitempty"`
}

// TargetDbObservation reflects the observed state from the upstream provider.
type TargetDbObservation struct {
}

// TargetDbSpec is the desired state of the resource.
type TargetDbSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetDbParameters `json:"forProvider"`
}

// TargetDbStatus reflects the observed state of the resource.
type TargetDbStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetDbObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetDb struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetDbSpec   `json:"spec"`
	Status            TargetDbStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetDbList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetDb `json:"items"`
}
