// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetDb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetDb) DeepCopy() *TargetDb {
	if in == nil {
		return nil
	}
	out := new(TargetDb)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetDb) DeepCopyInto(out *TargetDb) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetDbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetDbList) DeepCopy() *TargetDbList {
	if in == nil {
		return nil
	}
	out := new(TargetDbList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetDbList) DeepCopyInto(out *TargetDbList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetDb, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
