// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetLetsEncryptParameters defines the desired state of the resource.
type TargetLetsEncryptParameters struct {
	// +optional
	AcmeChallenge *string `json:"acme_challenge,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Name of existing cloud target for DNS credentials. Required when acme-challenge=dns. Supported: AWS, Azure, GCP, Cloudflare targets
	// +optional
	DnsTargetCreds *string `json:"dns_target_creds,omitempty"`
	// Cloudflare DNS zone identifier. Required when dns-target-creds points to Cloudflare target
	// +optional
	DnsZone *string `json:"dns_zone,omitempty"`
	// Email address for ACME account registration
	// +kubebuilder:validation:Required
	Email string `json:"email"`
	// GCP Cloud DNS: Project ID. Optional - can be derived from service account
	// +optional
	GcpProject *string `json:"gcp_project,omitempty"`
	// AWS Route53 hosted zone ID. Required when dns-target-creds points to AWS target
	// +optional
	HostedZone *string `json:"hosted_zone,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// +optional
	LetsEncryptUrl *string `json:"lets_encrypt_url,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Azure resource group name. Required when dns-target-creds points to Azure target
	// +optional
	ResourceGroup *string `json:"resource_group,omitempty"`
	// +optional
	Timeout *string `json:"timeout,omitempty"`
}

// TargetLetsEncryptObservation reflects the observed state from the upstream provider.
type TargetLetsEncryptObservation struct {
}

// TargetLetsEncryptSpec is the desired state of the resource.
type TargetLetsEncryptSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetLetsEncryptParameters `json:"forProvider"`
}

// TargetLetsEncryptStatus reflects the observed state of the resource.
type TargetLetsEncryptStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetLetsEncryptObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetLetsEncrypt struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetLetsEncryptSpec   `json:"spec"`
	Status            TargetLetsEncryptStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetLetsEncryptList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetLetsEncrypt `json:"items"`
}
