// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetLetsEncrypt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetLetsEncrypt) DeepCopy() *TargetLetsEncrypt {
	if in == nil {
		return nil
	}
	out := new(TargetLetsEncrypt)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetLetsEncrypt) DeepCopyInto(out *TargetLetsEncrypt) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetLetsEncryptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetLetsEncryptList) DeepCopy() *TargetLetsEncryptList {
	if in == nil {
		return nil
	}
	out := new(TargetLetsEncryptList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetLetsEncryptList) DeepCopyInto(out *TargetLetsEncryptList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetLetsEncrypt, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
