// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodSamlParameters defines the desired state of the resource.
type AuthMethodSamlParameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Allowed redirect URIs after SAML login
	// +optional
	AllowedRedirectUri *string `json:"allowed_redirect_uri,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// IDP metadata URL
	// +optional
	IdpMetadataUrl *string `json:"idp_metadata_url,omitempty"`
	// IDP metadata XML data (base64)
	// +optional
	IdpMetadataXmlData *string `json:"idp_metadata_xml_data,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
	// Delimiters for subclaim splitting
	// +optional
	SubclaimsDelimiters *string `json:"subclaims_delimiters,omitempty"`
	// Unique identifier attribute name in the SAML assertion
	// +kubebuilder:validation:Required
	UniqueIdentifier string `json:"unique_identifier"`
}

// AuthMethodSamlObservation reflects the observed state from the upstream provider.
type AuthMethodSamlObservation struct {
}

// AuthMethodSamlSpec is the desired state of the resource.
type AuthMethodSamlSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodSamlParameters `json:"forProvider"`
}

// AuthMethodSamlStatus reflects the observed state of the resource.
type AuthMethodSamlStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodSamlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodSaml struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodSamlSpec   `json:"spec"`
	Status            AuthMethodSamlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodSamlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodSaml `json:"items"`
}
