// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodSaml) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodSaml) DeepCopy() *AuthMethodSaml {
	if in == nil {
		return nil
	}
	out := new(AuthMethodSaml)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodSaml) DeepCopyInto(out *AuthMethodSaml) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodSamlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodSamlList) DeepCopy() *AuthMethodSamlList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodSamlList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodSamlList) DeepCopyInto(out *AuthMethodSamlList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodSaml, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
