// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayLogForwardingLogstashParameters defines the desired state of the resource.
type GatewayLogForwardingLogstashParameters struct {
	// Logstash dns
	// +optional
	Dns *string `json:"dns,omitempty"`
	// Enable Log Forwarding [true/false]
	// +optional
	Enable *string `json:"enable,omitempty"`
	// Enable tls
	// +optional
	EnableTls *bool `json:"enable_tls,omitempty"`
	// Logs format [text/json]
	// +optional
	OutputFormat *string `json:"output_format,omitempty"`
	// Logstash protocol [tcp/udp]
	// +optional
	Protocol *string `json:"protocol,omitempty"`
	// Pull interval in seconds
	// +optional
	PullInterval *string `json:"pull_interval,omitempty"`
	// Logstash tls certificate
	// +optional
	TlsCertificate *string `json:"tls_certificate,omitempty"`
}

// GatewayLogForwardingLogstashObservation reflects the observed state from the upstream provider.
type GatewayLogForwardingLogstashObservation struct {
}

// GatewayLogForwardingLogstashSpec is the desired state of the resource.
type GatewayLogForwardingLogstashSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayLogForwardingLogstashParameters `json:"forProvider"`
}

// GatewayLogForwardingLogstashStatus reflects the observed state of the resource.
type GatewayLogForwardingLogstashStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayLogForwardingLogstashObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayLogForwardingLogstash struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayLogForwardingLogstashSpec   `json:"spec"`
	Status            GatewayLogForwardingLogstashStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayLogForwardingLogstashList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayLogForwardingLogstash `json:"items"`
}
