// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayLogForwardingLogstash) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingLogstash) DeepCopy() *GatewayLogForwardingLogstash {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingLogstash)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingLogstash) DeepCopyInto(out *GatewayLogForwardingLogstash) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayLogForwardingLogstashList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingLogstashList) DeepCopy() *GatewayLogForwardingLogstashList {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingLogstashList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingLogstashList) DeepCopyInto(out *GatewayLogForwardingLogstashList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayLogForwardingLogstash, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
