// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DfcKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DfcKey) DeepCopy() *DfcKey {
	if in == nil {
		return nil
	}
	out := new(DfcKey)
	in.DeepCopyInto(out)
	return out
}

func (in *DfcKey) DeepCopyInto(out *DfcKey) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DfcKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DfcKeyList) DeepCopy() *DfcKeyList {
	if in == nil {
		return nil
	}
	out := new(DfcKeyList)
	in.DeepCopyInto(out)
	return out
}

func (in *DfcKeyList) DeepCopyInto(out *DfcKeyList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DfcKey, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
