// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerMongoParameters defines the desired state of the resource.
type GatewayProducerMongoParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// MongoDB Atlas private key
	// +optional
	MongodbAtlasApiPrivateKey *string `json:"mongodb_atlas_api_private_key,omitempty"`
	// MongoDB Atlas public key
	// +optional
	MongodbAtlasApiPublicKey *string `json:"mongodb_atlas_api_public_key,omitempty"`
	// MongoDB Atlas project ID
	// +optional
	MongodbAtlasProjectId *string `json:"mongodb_atlas_project_id,omitempty"`
	// MongoDB custom data
	// +optional
	MongodbCustomData *string `json:"mongodb_custom_data,omitempty"`
	// MongoDB server default authentication database
	// +optional
	MongodbDefaultAuthDb *string `json:"mongodb_default_auth_db,omitempty"`
	// MongoDB server host and port
	// +optional
	MongodbHostPort *string `json:"mongodb_host_port,omitempty"`
	// MongoDB Name
	// +optional
	MongodbName *string `json:"mongodb_name,omitempty"`
	// MongoDB server password. You will prompted to provide a password if it will not appear in CLI parameters
	// +optional
	MongodbPassword *string `json:"mongodb_password,omitempty"`
	// MongoDB Roles
	// +optional
	MongodbRoles *string `json:"mongodb_roles,omitempty"`
	// MongoDB Scopes (Atlas only)
	// +optional
	MongodbScopes *string `json:"mongodb_scopes,omitempty"`
	// MongoDB server URI
	// +optional
	MongodbServerUri *string `json:"mongodb_server_uri,omitempty"`
	// MongoDB server URI options
	// +optional
	MongodbUriOptions *string `json:"mongodb_uri_options,omitempty"`
	// MongoDB server username
	// +optional
	MongodbUsername *string `json:"mongodb_username,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Encrypt producer with following key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerMongoObservation reflects the observed state from the upstream provider.
type GatewayProducerMongoObservation struct {
}

// GatewayProducerMongoSpec is the desired state of the resource.
type GatewayProducerMongoSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerMongoParameters `json:"forProvider"`
}

// GatewayProducerMongoStatus reflects the observed state of the resource.
type GatewayProducerMongoStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerMongoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerMongo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerMongoSpec   `json:"spec"`
	Status            GatewayProducerMongoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerMongoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerMongo `json:"items"`
}
