// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerMongo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerMongo) DeepCopy() *GatewayProducerMongo {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerMongo)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerMongo) DeepCopyInto(out *GatewayProducerMongo) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerMongoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerMongoList) DeepCopy() *GatewayProducerMongoList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerMongoList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerMongoList) DeepCopyInto(out *GatewayProducerMongoList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerMongo, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
