// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretLdapParameters defines the desired state of the resource.
type DynamicSecretLdapParameters struct {
	// +optional
	ProviderType *string `json:"ProviderType,omitempty"`
	// LDAP bind DN
	// +optional
	BindDn *string `json:"bind_dn,omitempty"`
	// LDAP bind DN password
	// +optional
	BindDnPassword *string `json:"bind_dn_password,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// External username for fixed mode
	// +optional
	ExternalUsername *string `json:"external_username,omitempty"`
	// For externally provided users, denotes the key-name of IdP claim to extract the username from (relevant only for external-username=true)
	// +optional
	FixedUserClaimKeyname *string `json:"fixed_user_claim_keyname,omitempty"`
	// Group DN for dynamic users
	// +optional
	GroupDn *string `json:"group_dn,omitempty"`
	// Host provider type [explicit/target], Default Host provider is explicit, Relevant only for Secure Remote Access of ssh cert issuer, ldap rotated secret and ldap dynamic secret
	// +optional
	HostProvider *string `json:"host_provider,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// CA Certificate File Content
	// +optional
	LdapCaCert *string `json:"ldap_ca_cert,omitempty"`
	// LDAP server URL
	// +optional
	LdapUrl *string `json:"ldap_url,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// RD Gateway server
	// +optional
	SecureAccessRdGatewayServer *string `json:"secure_access_rd_gateway_server,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// A list of linked targets to be associated, Relevant only for Secure Remote Access for ssh cert issuer, ldap rotated secret and ldap dynamic secret, To specify multiple targets use argument multiple times
	// +optional
	Target *string `json:"target,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// LDAP token expiration in seconds
	// +optional
	TokenExpiration *string `json:"token_expiration,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// LDAP user attribute
	// +optional
	UserAttribute *string `json:"user_attribute,omitempty"`
	// Base DN for user creation
	// +optional
	UserDn *string `json:"user_dn,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretLdapObservation reflects the observed state from the upstream provider.
type DynamicSecretLdapObservation struct {
}

// DynamicSecretLdapSpec is the desired state of the resource.
type DynamicSecretLdapSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretLdapParameters `json:"forProvider"`
}

// DynamicSecretLdapStatus reflects the observed state of the resource.
type DynamicSecretLdapStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretLdapObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretLdap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretLdapSpec   `json:"spec"`
	Status            DynamicSecretLdapStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretLdapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretLdap `json:"items"`
}
