// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretLdap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretLdap) DeepCopy() *DynamicSecretLdap {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretLdap)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretLdap) DeepCopyInto(out *DynamicSecretLdap) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretLdapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretLdapList) DeepCopy() *DynamicSecretLdapList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretLdapList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretLdapList) DeepCopyInto(out *DynamicSecretLdapList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretLdap, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
