// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetGemini) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGemini) DeepCopy() *TargetGemini {
	if in == nil {
		return nil
	}
	out := new(TargetGemini)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGemini) DeepCopyInto(out *TargetGemini) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetGeminiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGeminiList) DeepCopy() *TargetGeminiList {
	if in == nil {
		return nil
	}
	out := new(TargetGeminiList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGeminiList) DeepCopyInto(out *TargetGeminiList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetGemini, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
