// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerArtifactoryParameters defines the desired state of the resource.
type GatewayProducerArtifactoryParameters struct {
	// Artifactory Admin Name
	// +optional
	ArtifactoryAdminName *string `json:"artifactory_admin_name,omitempty"`
	// Artifactory Admin password
	// +optional
	ArtifactoryAdminPwd *string `json:"artifactory_admin_pwd,omitempty"`
	// Token Audience
	// +kubebuilder:validation:Required
	ArtifactoryTokenAudience string `json:"artifactory_token_audience"`
	// Token Scope
	// +kubebuilder:validation:Required
	ArtifactoryTokenScope string `json:"artifactory_token_scope"`
	// Base URL
	// +optional
	BaseUrl *string `json:"base_url,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerArtifactoryObservation reflects the observed state from the upstream provider.
type GatewayProducerArtifactoryObservation struct {
}

// GatewayProducerArtifactorySpec is the desired state of the resource.
type GatewayProducerArtifactorySpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerArtifactoryParameters `json:"forProvider"`
}

// GatewayProducerArtifactoryStatus reflects the observed state of the resource.
type GatewayProducerArtifactoryStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerArtifactoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerArtifactory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerArtifactorySpec   `json:"spec"`
	Status            GatewayProducerArtifactoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerArtifactoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerArtifactory `json:"items"`
}
