// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerArtifactory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerArtifactory) DeepCopy() *GatewayProducerArtifactory {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerArtifactory)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerArtifactory) DeepCopyInto(out *GatewayProducerArtifactory) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerArtifactoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerArtifactoryList) DeepCopy() *GatewayProducerArtifactoryList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerArtifactoryList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerArtifactoryList) DeepCopyInto(out *GatewayProducerArtifactoryList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerArtifactory, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
