// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetArtifactoryParameters defines the desired state of the resource.
type TargetArtifactoryParameters struct {
	// Artifactory admin username
	// +kubebuilder:validation:Required
	ArtifactoryAdminName string `json:"artifactory_admin_name"`
	// Artifactory admin password
	// +kubebuilder:validation:Required
	ArtifactoryAdminPwd string `json:"artifactory_admin_pwd"`
	// Artifactory base URL
	// +kubebuilder:validation:Required
	BaseUrl string `json:"base_url"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// The name of a key used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
}

// TargetArtifactoryObservation reflects the observed state from the upstream provider.
type TargetArtifactoryObservation struct {
}

// TargetArtifactorySpec is the desired state of the resource.
type TargetArtifactorySpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetArtifactoryParameters `json:"forProvider"`
}

// TargetArtifactoryStatus reflects the observed state of the resource.
type TargetArtifactoryStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetArtifactoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetArtifactory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetArtifactorySpec   `json:"spec"`
	Status            TargetArtifactoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetArtifactoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetArtifactory `json:"items"`
}
