// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetArtifactory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetArtifactory) DeepCopy() *TargetArtifactory {
	if in == nil {
		return nil
	}
	out := new(TargetArtifactory)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetArtifactory) DeepCopyInto(out *TargetArtifactory) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetArtifactoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetArtifactoryList) DeepCopy() *TargetArtifactoryList {
	if in == nil {
		return nil
	}
	out := new(TargetArtifactoryList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetArtifactoryList) DeepCopyInto(out *TargetArtifactoryList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetArtifactory, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
