// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerVenafiParameters defines the desired state of the resource.
type GatewayProducerVenafiParameters struct {
	// Admin credentials rotation interval (days)
	// +optional
	AdminRotationIntervalDays *int64 `json:"admin_rotation_interval_days,omitempty"`
	// Allow subdomains
	// +optional
	AllowSubdomains *bool `json:"allow_subdomains,omitempty"`
	// Allowed domains
	// +optional
	AllowedDomains *string `json:"allowed_domains,omitempty"`
	// Auto generated folder
	// +optional
	AutoGeneratedFolder *string `json:"auto_generated_folder,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Automatic admin credentials rotation
	// +optional
	EnableAdminRotation *bool `json:"enable_admin_rotation,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Root first in chain
	// +optional
	RootFirstInChain *bool `json:"root_first_in_chain,omitempty"`
	// Use Akeyless PKI issuer or Venafi issuer
	// +optional
	SignUsingAkeylessPki *bool `json:"sign_using_akeyless_pki,omitempty"`
	// Signer key name
	// +optional
	SignerKeyName *string `json:"signer_key_name,omitempty"`
	// Store private key
	// +optional
	StorePrivateKey *bool `json:"store_private_key,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL in time.Duration format (2160h / 129600m / etc...). When using sign-using-akeyless-pki certificates created will have this validity period, otherwise the user-ttl is taken from the Validity Period field of the Zone's' Issuing Template. When using cert-manager it is advised to have a TTL of above 60 days (1440h). For more information - https://cert-manager.io/docs/usage/certificate/
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
	// Venafi Access Token to use to access the TPP environment (Relevant when using TPP)
	// +optional
	VenafiAccessToken *string `json:"venafi_access_token,omitempty"`
	// Venafi API key
	// +optional
	VenafiApiKey *string `json:"venafi_api_key,omitempty"`
	// Venafi Baseurl
	// +optional
	VenafiBaseurl *string `json:"venafi_baseurl,omitempty"`
	// Venafi Client ID that was used when the access token was generated
	// +optional
	VenafiClientId *string `json:"venafi_client_id,omitempty"`
	// Venafi Refresh Token to use when the Access Token is expired (Relevant when using TPP)
	// +optional
	VenafiRefreshToken *string `json:"venafi_refresh_token,omitempty"`
	// Venafi using TPP
	// +optional
	VenafiUseTpp *bool `json:"venafi_use_tpp,omitempty"`
	// Venafi Zone
	// +optional
	VenafiZone *string `json:"venafi_zone,omitempty"`
}

// GatewayProducerVenafiObservation reflects the observed state from the upstream provider.
type GatewayProducerVenafiObservation struct {
}

// GatewayProducerVenafiSpec is the desired state of the resource.
type GatewayProducerVenafiSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerVenafiParameters `json:"forProvider"`
}

// GatewayProducerVenafiStatus reflects the observed state of the resource.
type GatewayProducerVenafiStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerVenafiObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerVenafi struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerVenafiSpec   `json:"spec"`
	Status            GatewayProducerVenafiStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerVenafiList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerVenafi `json:"items"`
}
