// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayMigration) DeepCopy() *GatewayMigration {
	if in == nil {
		return nil
	}
	out := new(GatewayMigration)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayMigration) DeepCopyInto(out *GatewayMigration) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayMigrationList) DeepCopy() *GatewayMigrationList {
	if in == nil {
		return nil
	}
	out := new(GatewayMigrationList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayMigrationList) DeepCopyInto(out *GatewayMigrationList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayMigration, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
