// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayLogForwardingStdoutParameters defines the desired state of the resource.
type GatewayLogForwardingStdoutParameters struct {
	// Enable Log Forwarding [true/false]
	// +optional
	Enable *string `json:"enable,omitempty"`
	// Logs format [text/json]
	// +optional
	OutputFormat *string `json:"output_format,omitempty"`
	// Pull interval in seconds
	// +optional
	PullInterval *string `json:"pull_interval,omitempty"`
}

// GatewayLogForwardingStdoutObservation reflects the observed state from the upstream provider.
type GatewayLogForwardingStdoutObservation struct {
}

// GatewayLogForwardingStdoutSpec is the desired state of the resource.
type GatewayLogForwardingStdoutSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayLogForwardingStdoutParameters `json:"forProvider"`
}

// GatewayLogForwardingStdoutStatus reflects the observed state of the resource.
type GatewayLogForwardingStdoutStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayLogForwardingStdoutObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayLogForwardingStdout struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayLogForwardingStdoutSpec   `json:"spec"`
	Status            GatewayLogForwardingStdoutStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayLogForwardingStdoutList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayLogForwardingStdout `json:"items"`
}
