// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayLogForwardingStdout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingStdout) DeepCopy() *GatewayLogForwardingStdout {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingStdout)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingStdout) DeepCopyInto(out *GatewayLogForwardingStdout) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayLogForwardingStdoutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingStdoutList) DeepCopy() *GatewayLogForwardingStdoutList {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingStdoutList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingStdoutList) DeepCopyInto(out *GatewayLogForwardingStdoutList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayLogForwardingStdout, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
