// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretOpenai) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretOpenai) DeepCopy() *RotatedSecretOpenai {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretOpenai)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretOpenai) DeepCopyInto(out *RotatedSecretOpenai) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretOpenaiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretOpenaiList) DeepCopy() *RotatedSecretOpenaiList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretOpenaiList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretOpenaiList) DeepCopyInto(out *RotatedSecretOpenaiList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretOpenai, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
