// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetGithub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGithub) DeepCopy() *TargetGithub {
	if in == nil {
		return nil
	}
	out := new(TargetGithub)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGithub) DeepCopyInto(out *TargetGithub) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetGithubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGithubList) DeepCopy() *TargetGithubList {
	if in == nil {
		return nil
	}
	out := new(TargetGithubList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGithubList) DeepCopyInto(out *TargetGithubList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetGithub, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
