// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetPing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetPing) DeepCopy() *TargetPing {
	if in == nil {
		return nil
	}
	out := new(TargetPing)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetPing) DeepCopyInto(out *TargetPing) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetPingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetPingList) DeepCopy() *TargetPingList {
	if in == nil {
		return nil
	}
	out := new(TargetPingList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetPingList) DeepCopyInto(out *TargetPingList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetPing, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
