// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerRdp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerRdp) DeepCopy() *GatewayProducerRdp {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerRdp)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerRdp) DeepCopyInto(out *GatewayProducerRdp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerRdpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerRdpList) DeepCopy() *GatewayProducerRdpList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerRdpList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerRdpList) DeepCopyInto(out *GatewayProducerRdpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerRdp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
