// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KmipClientParameters defines the desired state of the resource.
type KmipClientParameters struct {
	// If set to 'true', newly created keys on the client will be set to an 'active' state
	// +optional
	ActivateKeysOnCreation *string `json:"activate_keys_on_creation,omitempty"`
	// Client certificate TTL in days
	// +optional
	CertificateTtl *int64 `json:"certificate_ttl,omitempty"`
	// How many days before the expiration of the certificate would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Client name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
}

// KmipClientObservation reflects the observed state from the upstream provider.
type KmipClientObservation struct {
}

// KmipClientSpec is the desired state of the resource.
type KmipClientSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       KmipClientParameters `json:"forProvider"`
}

// KmipClientStatus reflects the observed state of the resource.
type KmipClientStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          KmipClientObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type KmipClient struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KmipClientSpec   `json:"spec"`
	Status            KmipClientStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type KmipClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KmipClient `json:"items"`
}
