// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *KmipClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KmipClient) DeepCopy() *KmipClient {
	if in == nil {
		return nil
	}
	out := new(KmipClient)
	in.DeepCopyInto(out)
	return out
}

func (in *KmipClient) DeepCopyInto(out *KmipClient) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *KmipClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KmipClientList) DeepCopy() *KmipClientList {
	if in == nil {
		return nil
	}
	out := new(KmipClientList)
	in.DeepCopyInto(out)
	return out
}

func (in *KmipClientList) DeepCopyInto(out *KmipClientList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KmipClient, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
