// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetHashiVaultParameters defines the desired state of the resource.
type TargetHashiVaultParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// HashiCorp Vault API URL, e.g. https://vault-mgr01:8200
	// +optional
	HashiUrl *string `json:"hashi_url,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Comma-separated list of vault namespaces
	// +optional
	Namespace *string `json:"namespace,omitempty"`
	// HashiCorp Vault token
	// +optional
	VaultToken *string `json:"vault_token,omitempty"`
}

// TargetHashiVaultObservation reflects the observed state from the upstream provider.
type TargetHashiVaultObservation struct {
}

// TargetHashiVaultSpec is the desired state of the resource.
type TargetHashiVaultSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetHashiVaultParameters `json:"forProvider"`
}

// TargetHashiVaultStatus reflects the observed state of the resource.
type TargetHashiVaultStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetHashiVaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetHashiVault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetHashiVaultSpec   `json:"spec"`
	Status            TargetHashiVaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetHashiVaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetHashiVault `json:"items"`
}
