// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetHashiVault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetHashiVault) DeepCopy() *TargetHashiVault {
	if in == nil {
		return nil
	}
	out := new(TargetHashiVault)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetHashiVault) DeepCopyInto(out *TargetHashiVault) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetHashiVaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetHashiVaultList) DeepCopy() *TargetHashiVaultList {
	if in == nil {
		return nil
	}
	out := new(TargetHashiVaultList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetHashiVaultList) DeepCopyInto(out *TargetHashiVaultList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetHashiVault, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
