// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *EventForwarderServicenow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderServicenow) DeepCopy() *EventForwarderServicenow {
	if in == nil {
		return nil
	}
	out := new(EventForwarderServicenow)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderServicenow) DeepCopyInto(out *EventForwarderServicenow) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *EventForwarderServicenowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderServicenowList) DeepCopy() *EventForwarderServicenowList {
	if in == nil {
		return nil
	}
	out := new(EventForwarderServicenowList)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderServicenowList) DeepCopyInto(out *EventForwarderServicenowList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EventForwarderServicenow, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
