// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayLogForwardingAwsS3Parameters defines the desired state of the resource.
type GatewayLogForwardingAwsS3Parameters struct {
	// AWS access id relevant for access_key auth-type
	// +optional
	AccessId *string `json:"access_id,omitempty"`
	// AWS access key relevant for access_key auth-type
	// +optional
	AccessKey *string `json:"access_key,omitempty"`
	// AWS auth type [access_key/cloud_id/assume_role]
	// +optional
	AuthType *string `json:"auth_type,omitempty"`
	// AWS S3 bucket name
	// +optional
	BucketName *string `json:"bucket_name,omitempty"`
	// Enable Log Forwarding [true/false]
	// +optional
	Enable *string `json:"enable,omitempty"`
	// AWS S3 destination folder for logs
	// +optional
	LogFolder *string `json:"log_folder,omitempty"`
	// Logs format [text/json]
	// +optional
	OutputFormat *string `json:"output_format,omitempty"`
	// Pull interval in seconds
	// +optional
	PullInterval *string `json:"pull_interval,omitempty"`
	// AWS region
	// +optional
	Region *string `json:"region,omitempty"`
	// AWS role arn relevant for assume_role auth-type
	// +optional
	RoleArn *string `json:"role_arn,omitempty"`
}

// GatewayLogForwardingAwsS3Observation reflects the observed state from the upstream provider.
type GatewayLogForwardingAwsS3Observation struct {
}

// GatewayLogForwardingAwsS3Spec is the desired state of the resource.
type GatewayLogForwardingAwsS3Spec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayLogForwardingAwsS3Parameters `json:"forProvider"`
}

// GatewayLogForwardingAwsS3Status reflects the observed state of the resource.
type GatewayLogForwardingAwsS3Status struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayLogForwardingAwsS3Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayLogForwardingAwsS3 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayLogForwardingAwsS3Spec   `json:"spec"`
	Status            GatewayLogForwardingAwsS3Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayLogForwardingAwsS3List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayLogForwardingAwsS3 `json:"items"`
}
