// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetEksParameters defines the desired state of the resource.
type TargetEksParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// AWS access key ID for EKS
	// +kubebuilder:validation:Required
	EksAccessKeyId string `json:"eks_access_key_id"`
	// EKS cluster CA certificate (PEM)
	// +kubebuilder:validation:Required
	EksClusterCaCert string `json:"eks_cluster_ca_cert"`
	// EKS cluster API server URL
	// +kubebuilder:validation:Required
	EksClusterEndpoint string `json:"eks_cluster_endpoint"`
	// EKS cluster name
	// +kubebuilder:validation:Required
	EksClusterName string `json:"eks_cluster_name"`
	// AWS region for EKS cluster
	// +optional
	EksRegion *string `json:"eks_region,omitempty"`
	// AWS secret access key for EKS
	// +kubebuilder:validation:Required
	EksSecretAccessKey string `json:"eks_secret_access_key"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Use gateway cloud identity for authentication
	// +optional
	UseGwCloudIdentity *bool `json:"use_gw_cloud_identity,omitempty"`
}

// TargetEksObservation reflects the observed state from the upstream provider.
type TargetEksObservation struct {
}

// TargetEksSpec is the desired state of the resource.
type TargetEksSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetEksParameters `json:"forProvider"`
}

// TargetEksStatus reflects the observed state of the resource.
type TargetEksStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetEksObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetEks struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetEksSpec   `json:"spec"`
	Status            TargetEksStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetEksList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetEks `json:"items"`
}
