// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetEks) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetEks) DeepCopy() *TargetEks {
	if in == nil {
		return nil
	}
	out := new(TargetEks)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetEks) DeepCopyInto(out *TargetEks) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetEksList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetEksList) DeepCopy() *TargetEksList {
	if in == nil {
		return nil
	}
	out := new(TargetEksList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetEksList) DeepCopyInto(out *TargetEksList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetEks, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
