// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetGcp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGcp) DeepCopy() *TargetGcp {
	if in == nil {
		return nil
	}
	out := new(TargetGcp)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGcp) DeepCopyInto(out *TargetGcp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetGcpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGcpList) DeepCopy() *TargetGcpList {
	if in == nil {
		return nil
	}
	out := new(TargetGcpList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGcpList) DeepCopyInto(out *TargetGcpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetGcp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
