// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretSsh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretSsh) DeepCopy() *RotatedSecretSsh {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretSsh)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretSsh) DeepCopyInto(out *RotatedSecretSsh) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretSshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretSshList) DeepCopy() *RotatedSecretSshList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretSshList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretSshList) DeepCopyInto(out *RotatedSecretSshList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretSsh, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
