// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerCustom) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerCustom) DeepCopy() *GatewayProducerCustom {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerCustom)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerCustom) DeepCopyInto(out *GatewayProducerCustom) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerCustomList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerCustomList) DeepCopy() *GatewayProducerCustomList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerCustomList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerCustomList) DeepCopyInto(out *GatewayProducerCustomList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerCustom, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
