// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretSnowflakeParameters defines the desired state of the resource.
type DynamicSecretSnowflakeParameters struct {
	// Account name
	// +optional
	Account *string `json:"account,omitempty"`
	// Database Password
	// +optional
	AccountPassword *string `json:"account_password,omitempty"`
	// Database Username
	// +optional
	AccountUsername *string `json:"account_username,omitempty"`
	// The authentication mode for the temporary user [password/key]
	// +optional
	AuthMode *string `json:"auth_mode,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Database name
	// +optional
	DbName *string `json:"db_name,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// +optional
	KeyAlgo *string `json:"key_algo,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// RSA Private key (base64 encoded)
	// +optional
	PrivateKey *string `json:"private_key,omitempty"`
	// The Private key passphrase
	// +optional
	PrivateKeyPassphrase *string `json:"private_key_passphrase,omitempty"`
	// User role
	// +optional
	Role *string `json:"role,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
	// Warehouse name
	// +optional
	Warehouse *string `json:"warehouse,omitempty"`
}

// DynamicSecretSnowflakeObservation reflects the observed state from the upstream provider.
type DynamicSecretSnowflakeObservation struct {
}

// DynamicSecretSnowflakeSpec is the desired state of the resource.
type DynamicSecretSnowflakeSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretSnowflakeParameters `json:"forProvider"`
}

// DynamicSecretSnowflakeStatus reflects the observed state of the resource.
type DynamicSecretSnowflakeStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretSnowflakeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretSnowflake struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretSnowflakeSpec   `json:"spec"`
	Status            DynamicSecretSnowflakeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretSnowflakeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretSnowflake `json:"items"`
}
