// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayLogForwardingDatadogParameters defines the desired state of the resource.
type GatewayLogForwardingDatadogParameters struct {
	// Datadog api key
	// +optional
	ApiKey *string `json:"api_key,omitempty"`
	// Enable Log Forwarding [true/false]
	// +optional
	Enable *string `json:"enable,omitempty"`
	// Datadog host
	// +optional
	Host *string `json:"host,omitempty"`
	// Datadog log service
	// +optional
	LogService *string `json:"log_service,omitempty"`
	// Datadog log source
	// +optional
	LogSource *string `json:"log_source,omitempty"`
	// A comma-separated list of Datadog log tags formatted as "key:value" strings
	// +optional
	LogTags *string `json:"log_tags,omitempty"`
	// Logs format [text/json]
	// +optional
	OutputFormat *string `json:"output_format,omitempty"`
	// Pull interval in seconds
	// +optional
	PullInterval *string `json:"pull_interval,omitempty"`
}

// GatewayLogForwardingDatadogObservation reflects the observed state from the upstream provider.
type GatewayLogForwardingDatadogObservation struct {
}

// GatewayLogForwardingDatadogSpec is the desired state of the resource.
type GatewayLogForwardingDatadogSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayLogForwardingDatadogParameters `json:"forProvider"`
}

// GatewayLogForwardingDatadogStatus reflects the observed state of the resource.
type GatewayLogForwardingDatadogStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayLogForwardingDatadogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayLogForwardingDatadog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayLogForwardingDatadogSpec   `json:"spec"`
	Status            GatewayLogForwardingDatadogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayLogForwardingDatadogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayLogForwardingDatadog `json:"items"`
}
