// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayLogForwardingDatadog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingDatadog) DeepCopy() *GatewayLogForwardingDatadog {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingDatadog)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingDatadog) DeepCopyInto(out *GatewayLogForwardingDatadog) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayLogForwardingDatadogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingDatadogList) DeepCopy() *GatewayLogForwardingDatadogList {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingDatadogList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingDatadogList) DeepCopyInto(out *GatewayLogForwardingDatadogList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayLogForwardingDatadog, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
