// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretCassandra) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretCassandra) DeepCopy() *DynamicSecretCassandra {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretCassandra)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretCassandra) DeepCopyInto(out *DynamicSecretCassandra) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretCassandraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretCassandraList) DeepCopy() *DynamicSecretCassandraList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretCassandraList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretCassandraList) DeepCopyInto(out *DynamicSecretCassandraList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretCassandra, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
