// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretAzure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretAzure) DeepCopy() *DynamicSecretAzure {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretAzure)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretAzure) DeepCopyInto(out *DynamicSecretAzure) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretAzureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretAzureList) DeepCopy() *DynamicSecretAzureList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretAzureList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretAzureList) DeepCopyInto(out *DynamicSecretAzureList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretAzure, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
