// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretGke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretGke) DeepCopy() *DynamicSecretGke {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretGke)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretGke) DeepCopyInto(out *DynamicSecretGke) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretGkeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretGkeList) DeepCopy() *DynamicSecretGkeList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretGkeList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretGkeList) DeepCopyInto(out *DynamicSecretGkeList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretGke, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
