// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerGkeParameters defines the desired state of the resource.
type GatewayProducerGkeParameters struct {
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// GKE Service Account key file path
	// +optional
	GkeAccountKey *string `json:"gke_account_key,omitempty"`
	// GKE cluster CA certificate
	// +optional
	GkeClusterCert *string `json:"gke_cluster_cert,omitempty"`
	// GKE cluster URL endpoint
	// +optional
	GkeClusterEndpoint *string `json:"gke_cluster_endpoint,omitempty"`
	// GKE cluster name
	// +optional
	GkeClusterName *string `json:"gke_cluster_name,omitempty"`
	// GKE service account email
	// +optional
	GkeServiceAccountEmail *string `json:"gke_service_account_email,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Enable Port forwarding while using CLI access
	// +optional
	SecureAccessAllowPortForwading *bool `json:"secure_access_allow_port_forwading,omitempty"`
	// The K8s cluster endpoint URL
	// +optional
	SecureAccessClusterEndpoint *string `json:"secure_access_cluster_endpoint,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerGkeObservation reflects the observed state from the upstream provider.
type GatewayProducerGkeObservation struct {
}

// GatewayProducerGkeSpec is the desired state of the resource.
type GatewayProducerGkeSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerGkeParameters `json:"forProvider"`
}

// GatewayProducerGkeStatus reflects the observed state of the resource.
type GatewayProducerGkeStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerGkeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerGke struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerGkeSpec   `json:"spec"`
	Status            GatewayProducerGkeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerGkeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerGke `json:"items"`
}
