// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetSectigoParameters defines the desired state of the resource.
type TargetSectigoParameters struct {
	// Certificate Profile ID in Sectigo account
	// +kubebuilder:validation:Required
	CertificateProfileId int64 `json:"certificate_profile_id"`
	// Customer Uri of the Sectigo account
	// +kubebuilder:validation:Required
	CustomerUri string `json:"customer_uri"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// External Requester - a comma separated list of emails
	// +kubebuilder:validation:Required
	ExternalRequester string `json:"external_requester"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Organization ID in Sectigo account
	// +kubebuilder:validation:Required
	OrganizationId int64 `json:"organization_id"`
	// Timeout waiting for certificate validation in Duration format (1h - 1 Hour, 20m - 20 Minutes, 33m3s - 33 Minutes and 3 Seconds), maximum 1h.
	// +optional
	Timeout *string `json:"timeout,omitempty"`
}

// TargetSectigoObservation reflects the observed state from the upstream provider.
type TargetSectigoObservation struct {
}

// TargetSectigoSpec is the desired state of the resource.
type TargetSectigoSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetSectigoParameters `json:"forProvider"`
}

// TargetSectigoStatus reflects the observed state of the resource.
type TargetSectigoStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetSectigoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetSectigo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetSectigoSpec   `json:"spec"`
	Status            TargetSectigoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetSectigoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetSectigo `json:"items"`
}
