// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerDockerhub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerDockerhub) DeepCopy() *GatewayProducerDockerhub {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerDockerhub)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerDockerhub) DeepCopyInto(out *GatewayProducerDockerhub) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerDockerhubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerDockerhubList) DeepCopy() *GatewayProducerDockerhubList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerDockerhubList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerDockerhubList) DeepCopyInto(out *GatewayProducerDockerhubList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerDockerhub, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
