// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerMssqlParameters defines the desired state of the resource.
type GatewayProducerMssqlParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// CSV of allowed DB names for runtime selection when getting the secret value. Empty => use target DB only; "*" => any DB allowed; One or more names => user must choose from this list
	// +optional
	MssqlAllowedDbNames *string `json:"mssql_allowed_db_names,omitempty"`
	// MSSQL Creation statements
	// +optional
	MssqlCreateStatements *string `json:"mssql_create_statements,omitempty"`
	// MSSQL Name
	// +optional
	MssqlDbname *string `json:"mssql_dbname,omitempty"`
	// MSSQL Host
	// +optional
	MssqlHost *string `json:"mssql_host,omitempty"`
	// MSSQL Password
	// +optional
	MssqlPassword *string `json:"mssql_password,omitempty"`
	// MSSQL Port
	// +optional
	MssqlPort *string `json:"mssql_port,omitempty"`
	// MSSQL Revocation statements
	// +optional
	MssqlRevocationStatements *string `json:"mssql_revocation_statements,omitempty"`
	// MSSQL Username
	// +optional
	MssqlUsername *string `json:"mssql_username,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerMssqlObservation reflects the observed state from the upstream provider.
type GatewayProducerMssqlObservation struct {
}

// GatewayProducerMssqlSpec is the desired state of the resource.
type GatewayProducerMssqlSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerMssqlParameters `json:"forProvider"`
}

// GatewayProducerMssqlStatus reflects the observed state of the resource.
type GatewayProducerMssqlStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerMssqlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerMssql struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerMssqlSpec   `json:"spec"`
	Status            GatewayProducerMssqlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerMssqlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerMssql `json:"items"`
}
