// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerMssql) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerMssql) DeepCopy() *GatewayProducerMssql {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerMssql)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerMssql) DeepCopyInto(out *GatewayProducerMssql) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerMssqlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerMssqlList) DeepCopy() *GatewayProducerMssqlList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerMssqlList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerMssqlList) DeepCopyInto(out *GatewayProducerMssqlList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerMssql, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
