// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretPing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretPing) DeepCopy() *DynamicSecretPing {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretPing)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretPing) DeepCopyInto(out *DynamicSecretPing) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretPingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretPingList) DeepCopy() *DynamicSecretPingList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretPingList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretPingList) DeepCopyInto(out *DynamicSecretPingList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretPing, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
