// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretHanadbParameters defines the desired state of the resource.
type DynamicSecretHanadbParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// HanaDb Name
	// +optional
	HanaDbname *string `json:"hana_dbname,omitempty"`
	// HanaDb Creation statements
	// +optional
	HanadbCreateStatements *string `json:"hanadb_create_statements,omitempty"`
	// HANA host
	// +optional
	HanadbHost *string `json:"hanadb_host,omitempty"`
	// HANA admin password
	// +optional
	HanadbPassword *string `json:"hanadb_password,omitempty"`
	// HANA port (default: 443)
	// +optional
	HanadbPort *string `json:"hanadb_port,omitempty"`
	// HANA SQL revocation statements
	// +optional
	HanadbRevocationStatements *string `json:"hanadb_revocation_statements,omitempty"`
	// HANA admin username
	// +optional
	HanadbUsername *string `json:"hanadb_username,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretHanadbObservation reflects the observed state from the upstream provider.
type DynamicSecretHanadbObservation struct {
}

// DynamicSecretHanadbSpec is the desired state of the resource.
type DynamicSecretHanadbSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretHanadbParameters `json:"forProvider"`
}

// DynamicSecretHanadbStatus reflects the observed state of the resource.
type DynamicSecretHanadbStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretHanadbObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretHanadb struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretHanadbSpec   `json:"spec"`
	Status            DynamicSecretHanadbStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretHanadbList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretHanadb `json:"items"`
}
