// Code generated by iac-forge. DO NOT EDIT.

package dynamicsecrethanadb

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/logging"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	akeyless "github.com/pleme-io/akeyless-go"
	providerv1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/akeyless/v1alpha1"
	v1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/dynamicsecrethanadb/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// akeylessCredentials is the JSON shape the controller expects from the
// ProviderConfig's referenced Secret. Both akeyless's snake_case and the
// akeyless-CLI's hyphenated variants are accepted.
type akeylessCredentials struct {
	AccessID      string `json:"access_id,omitempty"`
	AccessKey     string `json:"access_key,omitempty"`
	AccessIDDash  string `json:"access-id,omitempty"`
	AccessKeyDash string `json:"access-key,omitempty"`
}

// external is the per-cluster reconciler that owns the SDK client and
// the token resolved from the bound ProviderConfig.
type external struct {
	client *akeyless.APIClient
	token  string
}

// Setup wires this resource's controller into the manager.
func Setup(mgr ctrl.Manager, pollInterval time.Duration) error {
	name := "DynamicSecretHanadb"
	gvk := v1alpha1.GroupVersion.WithKind("DynamicSecretHanadb")
	r := managed.NewReconciler(mgr, resource.ManagedKind(gvk), managed.WithExternalConnecter(&connector{
		kube: mgr.GetClient(),
	}), managed.WithPollInterval(pollInterval), managed.WithLogger(logging.NewLogrLogger(ctrl.Log.WithName(name))))
	return ctrl.NewControllerManagedBy(mgr).Named(name).For(&v1alpha1.DynamicSecretHanadb{}).Complete(r)
}

// connector resolves a ProviderConfig and constructs an external
// client for each managed-resource reconcile loop.
type connector struct {
	kube client.Client
}

func (c *connector) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*v1alpha1.DynamicSecretHanadb)
	if !ok {
		return nil, errors.New("expected *v1alpha1.DynamicSecretHanadb")
	}
	pcRef := cr.GetProviderConfigReference()
	if pcRef == nil {
		return nil, errors.New("no provider config reference")
	}

	pc := &providerv1alpha1.ProviderConfig{}
	if err := c.kube.Get(ctx, client.ObjectKey{
		Name: pcRef.Name,
	}, pc); err != nil {
		return nil, err
	}
	creds, err := resource.CommonCredentialExtractor(ctx, pc.Spec.Credentials.Source, c.kube, pc.Spec.Credentials.CommonCredentialSelectors)
	if err != nil {
		return nil, err
	}

	cfg := akeyless.NewConfiguration()
	if pc.Spec.APIGateway != "" {
		// TODO goast-slice-2: emit cfg.Servers via structured SliceLit
		cfg.Servers = []akeyless.ServerConfiguration{{URL: pc.Spec.APIGateway}}
	}

	// Decode the access-id + access-key from the credentials Secret.
	// Both keys are required: /auth exchanges them for a session token.
	akCreds := akeylessCredentials{}
	if err := json.Unmarshal(creds, &akCreds); err != nil {
		return nil, fmt.Errorf("akeyless credentials must be JSON {\"access_id\":\"...\",\"access_key\":\"...\"}: %w", err)
	}
	accessID := akCreds.AccessID
	if accessID == "" {
		accessID = akCreds.AccessIDDash
	}
	accessKey := akCreds.AccessKey
	if accessKey == "" {
		accessKey = akCreds.AccessKeyDash
	}
	if accessID == "" || accessKey == "" {
		return nil, errors.New("akeyless credentials missing access_id or access_key")
	}

	apiClient := akeyless.NewAPIClient(cfg)
	accessType := "access_key"
	authOut, _, err := apiClient.V2API.Auth(ctx).Auth(akeyless.Auth{
		AccessId:   &accessID,
		AccessKey:  &accessKey,
		AccessType: &accessType,
	}).Execute()
	if err != nil {
		return nil, fmt.Errorf("akeyless /auth exchange failed: %w", err)
	}
	if authOut == nil || authOut.Token == nil || *authOut.Token == "" {
		return nil, errors.New("akeyless /auth returned empty session token")
	}

	return &external{
		client: apiClient,
		token:  *authOut.Token,
	}, nil
}

// Observe queries the upstream provider for the resource's current state.
// The returned ExternalObservation tells the managed-resource reconciler
// (a) whether the resource exists upstream and (b) whether its observed
// state matches the declared spec.
func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.DynamicSecretHanadb)
	if !ok {
		return managed.ExternalObservation{}, errors.New("expected *v1alpha1.DynamicSecretHanadb")
	}

	body := akeyless.DynamicSecretGet{
		Name:  meta.GetExternalName(cr),
		Token: &e.token,
	}
	_, resp, err := e.client.V2API.DynamicSecretGet(ctx).DynamicSecretGet(body).Execute()
	if err != nil {
		// Observed an error. If the upstream API reports 404 the resource
		// is absent and the reconciler should advance to Create.
		if resp != nil && resp.StatusCode == http.StatusNotFound {
			return managed.ExternalObservation{
				ResourceExists: false,
			}, nil
		}
		return managed.ExternalObservation{}, err
	}

	cr.SetConditions(xpv1.Available())
	// ResourceUpToDate=true short-circuits the spec↔atProvider diff;
	// structural diff lands in controller-iter-2.
	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: true,
	}, nil
}

// Create provisions the resource upstream.
func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.DynamicSecretHanadb)
	if !ok {
		return managed.ExternalCreation{}, errors.New("expected *v1alpha1.DynamicSecretHanadb")
	}

	body := akeyless.DynamicSecretCreateHanaDb{
		Name:  meta.GetExternalName(cr),
		Token: &e.token,
	}
	// TODO controller-iter-2: map cr.Spec.ForProvider fields → body fields
	_, _, err := e.client.V2API.DynamicSecretCreateHanaDb(ctx).DynamicSecretCreateHanaDb(body).Execute()
	return managed.ExternalCreation{}, err
}

// Update reconciles the upstream resource against the declared spec.
func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.DynamicSecretHanadb)
	if !ok {
		return managed.ExternalUpdate{}, errors.New("expected *v1alpha1.DynamicSecretHanadb")
	}

	body := akeyless.DynamicSecretUpdateHanaDb{
		Name:  meta.GetExternalName(cr),
		Token: &e.token,
	}
	// TODO controller-iter-2: map mutable cr.Spec.ForProvider fields → body fields
	_, _, err := e.client.V2API.DynamicSecretUpdateHanaDb(ctx).DynamicSecretUpdateHanaDb(body).Execute()
	return managed.ExternalUpdate{}, err
}

// Delete removes the upstream resource. Idempotent on NotFound.
// Signature follows crossplane-runtime v1.18+: returns (ExternalDelete, error).
func (e *external) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.DynamicSecretHanadb)
	if !ok {
		return managed.ExternalDelete{}, errors.New("expected *v1alpha1.DynamicSecretHanadb")
	}

	body := akeyless.DynamicSecretDelete{
		Name:  meta.GetExternalName(cr),
		Token: &e.token,
	}
	_, resp, err := e.client.V2API.DynamicSecretDelete(ctx).DynamicSecretDelete(body).Execute()
	if err != nil && resp != nil && resp.StatusCode == http.StatusNotFound {
		return managed.ExternalDelete{}, nil
	}
	return managed.ExternalDelete{}, err
}

// Disconnect releases any per-cluster client resources. The akeyless SDK
// holds no long-lived resources beyond per-call request state, so this is
// a no-op. Required by crossplane-runtime v1.18+'s ExternalClient interface.
func (_ *external) Disconnect(_ context.Context) error {
	return nil
}
