// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayLogForwardingSumologic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingSumologic) DeepCopy() *GatewayLogForwardingSumologic {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingSumologic)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingSumologic) DeepCopyInto(out *GatewayLogForwardingSumologic) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayLogForwardingSumologicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingSumologicList) DeepCopy() *GatewayLogForwardingSumologicList {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingSumologicList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingSumologicList) DeepCopyInto(out *GatewayLogForwardingSumologicList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayLogForwardingSumologic, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
