// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetSalesforce) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSalesforce) DeepCopy() *TargetSalesforce {
	if in == nil {
		return nil
	}
	out := new(TargetSalesforce)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSalesforce) DeepCopyInto(out *TargetSalesforce) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetSalesforceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSalesforceList) DeepCopy() *TargetSalesforceList {
	if in == nil {
		return nil
	}
	out := new(TargetSalesforceList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSalesforceList) DeepCopyInto(out *TargetSalesforceList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetSalesforce, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
