// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodOauth2Parameters defines the desired state of the resource.
type AuthMethodOauth2Parameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// OAuth2 audience
	// +optional
	Audience *string `json:"audience,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// OAuth2 client IDs to restrict access
	// +optional
	BoundClientIds *string `json:"bound_client_ids,omitempty"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// CertificateFile Path to a file that contain the certificate in a PEM format.
	// +optional
	Cert *string `json:"cert,omitempty"`
	// CertificateFileData PEM Certificate in a Base64 format.
	// +optional
	CertFileData *string `json:"cert_file_data,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// Akeyless Gateway URL (Configuration Management port). Relevant only when the jwks-uri is accessible only from the gateway.
	// +optional
	GatewayUrl *string `json:"gateway_url,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// OAuth2 issuer URL
	// +optional
	Issuer *string `json:"issuer,omitempty"`
	// JWKS JSON data for token verification
	// +optional
	JwksJsonData *string `json:"jwks_json_data,omitempty"`
	// JWKS URI for token verification
	// +optional
	JwksUri *string `json:"jwks_uri,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
	// A list of additional sub claims delimiters (relevant only for SAML, OIDC, OAuth2/JWT)
	// +optional
	SubclaimsDelimiters *string `json:"subclaims_delimiters,omitempty"`
	// Unique identifier claim name in the JWT token
	// +kubebuilder:validation:Required
	UniqueIdentifier string `json:"unique_identifier"`
}

// AuthMethodOauth2Observation reflects the observed state from the upstream provider.
type AuthMethodOauth2Observation struct {
}

// AuthMethodOauth2Spec is the desired state of the resource.
type AuthMethodOauth2Spec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodOauth2Parameters `json:"forProvider"`
}

// AuthMethodOauth2Status reflects the observed state of the resource.
type AuthMethodOauth2Status struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodOauth2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodOauth2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodOauth2Spec   `json:"spec"`
	Status            AuthMethodOauth2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodOauth2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodOauth2 `json:"items"`
}
