// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretEks) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretEks) DeepCopy() *DynamicSecretEks {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretEks)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretEks) DeepCopyInto(out *DynamicSecretEks) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretEksList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretEksList) DeepCopy() *DynamicSecretEksList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretEksList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretEksList) DeepCopyInto(out *DynamicSecretEksList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretEks, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
