// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretRdp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretRdp) DeepCopy() *DynamicSecretRdp {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretRdp)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretRdp) DeepCopyInto(out *DynamicSecretRdp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretRdpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretRdpList) DeepCopy() *DynamicSecretRdpList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretRdpList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretRdpList) DeepCopyInto(out *DynamicSecretRdpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretRdp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
