// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UscParameters defines the desired state of the resource.
type UscParameters struct {
	// Use this option if the universal secrets value is a base64 encoded binary
	// +optional
	BinaryValue *bool `json:"binary_value,omitempty"`
	// Description of the universal secrets
	// +optional
	Description *string `json:"description,omitempty"`
	// The namespace (relevant for Hashi vault target)
	// +optional
	Namespace *string `json:"namespace,omitempty"`
	// +optional
	ObjectType *string `json:"object_type,omitempty"`
	// Optional, the passphrase that protects the private key within the pfx certificate (Relevant only for Azure KV certificates)
	// +optional
	PfxPassword *string `json:"pfx_password,omitempty"`
	// Optional, create secret in a specific region (GCP only). If empty, a global secret will be created (provider default).
	// +optional
	Region *string `json:"region,omitempty"`
	// Activation date for the secret on the remote endpoint, in UTC format: YYYY-MM-DDTHH:MM:SSZ
	// +optional
	RemoteSecretActivationDate *string `json:"remote_secret_activation_date,omitempty"`
	// Expiration time for the secret on the remote endpoint, in UTC format: YYYY-MM-DDTHH:MM:SSZ
	// +optional
	RemoteSecretExpires *string `json:"remote_secret_expires,omitempty"`
	// Name for the new universal secrets
	// +kubebuilder:validation:Required
	SecretName string `json:"secret_name"`
	// +optional
	SelectedRepositories *string `json:"selected_repositories,omitempty"`
	// Tags for the universal secrets
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Optional, The name of the remote key that used to encrypt the secret value (if empty, the default key will be used)
	// +optional
	UscEncryptionKey *string `json:"usc_encryption_key,omitempty"`
	// Name of the Universal Secrets Connector item
	// +kubebuilder:validation:Required
	UscName string `json:"usc_name"`
	// Value of the universal secrets item, either text or base64 encoded binary
	// +kubebuilder:validation:Required
	Value string `json:"value"`
}

// UscObservation reflects the observed state from the upstream provider.
type UscObservation struct {
}

// UscSpec is the desired state of the resource.
type UscSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       UscParameters `json:"forProvider"`
}

// UscStatus reflects the observed state of the resource.
type UscStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          UscObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Usc struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UscSpec   `json:"spec"`
	Status            UscStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type UscList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Usc `json:"items"`
}
