// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayLogForwardingSplunkParameters defines the desired state of the resource.
type GatewayLogForwardingSplunkParameters struct {
	// Enable Log Forwarding [true/false]
	// +optional
	Enable *string `json:"enable,omitempty"`
	// Enable batch forwarding [true/false]
	// +optional
	EnableBatch *string `json:"enable_batch,omitempty"`
	// Enable tls
	// +optional
	EnableTls *bool `json:"enable_tls,omitempty"`
	// Splunk index
	// +optional
	Index *string `json:"index,omitempty"`
	// Logs format [text/json]
	// +optional
	OutputFormat *string `json:"output_format,omitempty"`
	// Pull interval in seconds
	// +optional
	PullInterval *string `json:"pull_interval,omitempty"`
	// Splunk source
	// +optional
	Source *string `json:"source,omitempty"`
	// Splunk source type
	// +optional
	SourceType *string `json:"source_type,omitempty"`
	// Splunk token
	// +optional
	SplunkToken *string `json:"splunk_token,omitempty"`
	// Splunk server URL
	// +optional
	SplunkUrl *string `json:"splunk_url,omitempty"`
	// Splunk tls certificate
	// +optional
	TlsCertificate *string `json:"tls_certificate,omitempty"`
}

// GatewayLogForwardingSplunkObservation reflects the observed state from the upstream provider.
type GatewayLogForwardingSplunkObservation struct {
}

// GatewayLogForwardingSplunkSpec is the desired state of the resource.
type GatewayLogForwardingSplunkSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayLogForwardingSplunkParameters `json:"forProvider"`
}

// GatewayLogForwardingSplunkStatus reflects the observed state of the resource.
type GatewayLogForwardingSplunkStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayLogForwardingSplunkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayLogForwardingSplunk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayLogForwardingSplunkSpec   `json:"spec"`
	Status            GatewayLogForwardingSplunkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayLogForwardingSplunkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayLogForwardingSplunk `json:"items"`
}
