// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetGlobalsignParameters defines the desired state of the resource.
type TargetGlobalsignParameters struct {
	// Contact email
	// +kubebuilder:validation:Required
	ContactEmail string `json:"contact_email"`
	// Contact first name
	// +kubebuilder:validation:Required
	ContactFirstName string `json:"contact_first_name"`
	// Contact last name
	// +kubebuilder:validation:Required
	ContactLastName string `json:"contact_last_name"`
	// Contact phone number
	// +kubebuilder:validation:Required
	ContactPhone string `json:"contact_phone"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// GlobalSign profile ID
	// +kubebuilder:validation:Required
	ProfileId string `json:"profile_id"`
	// Timeout waiting for certificate validation in Duration format (1h - 1 Hour, 20m - 20 Minutes, 33m3s - 33 Minutes and 3 Seconds), maximum 1h.
	// +optional
	Timeout *string `json:"timeout,omitempty"`
}

// TargetGlobalsignObservation reflects the observed state from the upstream provider.
type TargetGlobalsignObservation struct {
}

// TargetGlobalsignSpec is the desired state of the resource.
type TargetGlobalsignSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetGlobalsignParameters `json:"forProvider"`
}

// TargetGlobalsignStatus reflects the observed state of the resource.
type TargetGlobalsignStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetGlobalsignObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetGlobalsign struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetGlobalsignSpec   `json:"spec"`
	Status            TargetGlobalsignStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetGlobalsignList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetGlobalsign `json:"items"`
}
