// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetOpenaiParameters defines the desired state of the resource.
type TargetOpenaiParameters struct {
	// API key for OpenAI
	// +optional
	ApiKey *string `json:"api_key,omitempty"`
	// API key ID
	// +optional
	ApiKeyId *string `json:"api_key_id,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Default model to use with OpenAI
	// +optional
	Model *string `json:"model,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Base URL of the OpenAI API
	// +optional
	OpenaiUrl *string `json:"openai_url,omitempty"`
	// Organization ID
	// +optional
	OrganizationId *string `json:"organization_id,omitempty"`
}

// TargetOpenaiObservation reflects the observed state from the upstream provider.
type TargetOpenaiObservation struct {
}

// TargetOpenaiSpec is the desired state of the resource.
type TargetOpenaiSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetOpenaiParameters `json:"forProvider"`
}

// TargetOpenaiStatus reflects the observed state of the resource.
type TargetOpenaiStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetOpenaiObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetOpenai struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetOpenaiSpec   `json:"spec"`
	Status            TargetOpenaiStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetOpenaiList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetOpenai `json:"items"`
}
