// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodGcp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodGcp) DeepCopy() *AuthMethodGcp {
	if in == nil {
		return nil
	}
	out := new(AuthMethodGcp)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodGcp) DeepCopyInto(out *AuthMethodGcp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodGcpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodGcpList) DeepCopy() *AuthMethodGcpList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodGcpList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodGcpList) DeepCopyInto(out *AuthMethodGcpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodGcp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
