// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodK8s) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodK8s) DeepCopy() *AuthMethodK8s {
	if in == nil {
		return nil
	}
	out := new(AuthMethodK8s)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodK8s) DeepCopyInto(out *AuthMethodK8s) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodK8sList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodK8sList) DeepCopy() *AuthMethodK8sList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodK8sList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodK8sList) DeepCopyInto(out *AuthMethodK8sList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodK8s, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
