// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretMysql) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretMysql) DeepCopy() *RotatedSecretMysql {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretMysql)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretMysql) DeepCopyInto(out *RotatedSecretMysql) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretMysqlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretMysqlList) DeepCopy() *RotatedSecretMysqlList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretMysqlList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretMysqlList) DeepCopyInto(out *RotatedSecretMysqlList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretMysql, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
