// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerAzureParameters defines the desired state of the resource.
type GatewayProducerAzureParameters struct {
	// Azure App Object Id
	// +optional
	AppObjId *string `json:"app_obj_id,omitempty"`
	// Azure AD administrative unit (relevant only when azure-user-portal-access=true)
	// +optional
	AzureAdministrativeUnit *string `json:"azure_administrative_unit,omitempty"`
	// Azure Client ID
	// +optional
	AzureClientId *string `json:"azure_client_id,omitempty"`
	// Azure Client Secret
	// +optional
	AzureClientSecret *string `json:"azure_client_secret,omitempty"`
	// Azure Tenant ID
	// +optional
	AzureTenantId *string `json:"azure_tenant_id,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// FixedUserClaimKeyname
	// +optional
	FixedUserClaimKeyname *string `json:"fixed_user_claim_keyname,omitempty"`
	// Fixed user
	// +optional
	FixedUserOnly *bool `json:"fixed_user_only,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic secret encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User Group Object Id
	// +optional
	UserGroupObjId *string `json:"user_group_obj_id,omitempty"`
	// Azure User portal access
	// +optional
	UserPortalAccess *bool `json:"user_portal_access,omitempty"`
	// User Principal Name
	// +optional
	UserPrincipalName *string `json:"user_principal_name,omitempty"`
	// Azure User programmatic access
	// +optional
	UserProgrammaticAccess *bool `json:"user_programmatic_access,omitempty"`
	// User Role Template Id
	// +optional
	UserRoleTemplateId *string `json:"user_role_template_id,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerAzureObservation reflects the observed state from the upstream provider.
type GatewayProducerAzureObservation struct {
}

// GatewayProducerAzureSpec is the desired state of the resource.
type GatewayProducerAzureSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerAzureParameters `json:"forProvider"`
}

// GatewayProducerAzureStatus reflects the observed state of the resource.
type GatewayProducerAzureStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerAzureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerAzure struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerAzureSpec   `json:"spec"`
	Status            GatewayProducerAzureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerAzureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerAzure `json:"items"`
}
