// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodEmailParameters defines the desired state of the resource.
type AuthMethodEmailParameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// Email address for this auth method
	// +kubebuilder:validation:Required
	Email string `json:"email"`
	// Enable MFA for this authentication method [True / False]
	// +optional
	EnableMfa *string `json:"enable_mfa,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Enable two-factor-authentication via [email/auth app]
	// +optional
	MfaType *string `json:"mfa_type,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
}

// AuthMethodEmailObservation reflects the observed state from the upstream provider.
type AuthMethodEmailObservation struct {
}

// AuthMethodEmailSpec is the desired state of the resource.
type AuthMethodEmailSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodEmailParameters `json:"forProvider"`
}

// AuthMethodEmailStatus reflects the observed state of the resource.
type AuthMethodEmailStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodEmailObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodEmail struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodEmailSpec   `json:"spec"`
	Status            AuthMethodEmailStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodEmailList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodEmail `json:"items"`
}
