// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetWindowsParameters defines the desired state of the resource.
type TargetWindowsParameters struct {
	// Client certificate (PEM)
	// +optional
	Certificate *string `json:"certificate,omitempty"`
	// Type of connection to Windows Server [credentials/parent-target]
	// +optional
	ConnectionType *string `json:"connection_type,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Windows domain
	// +optional
	Domain *string `json:"domain,omitempty"`
	// Windows host address
	// +kubebuilder:validation:Required
	Hostname string `json:"hostname"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Name of the parent target, relevant only when connection-type is parent-target
	// +optional
	ParentTargetName *string `json:"parent_target_name,omitempty"`
	// WinRM port (default: 5986)
	// +optional
	Port *string `json:"port,omitempty"`
	// Use TLS for WinRM connection
	// +optional
	UseTls *bool `json:"use_tls,omitempty"`
}

// TargetWindowsObservation reflects the observed state from the upstream provider.
type TargetWindowsObservation struct {
}

// TargetWindowsSpec is the desired state of the resource.
type TargetWindowsSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetWindowsParameters `json:"forProvider"`
}

// TargetWindowsStatus reflects the observed state of the resource.
type TargetWindowsStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetWindowsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetWindows struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetWindowsSpec   `json:"spec"`
	Status            TargetWindowsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetWindowsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetWindows `json:"items"`
}
