// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetWindows) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetWindows) DeepCopy() *TargetWindows {
	if in == nil {
		return nil
	}
	out := new(TargetWindows)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetWindows) DeepCopyInto(out *TargetWindows) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetWindowsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetWindowsList) DeepCopy() *TargetWindowsList {
	if in == nil {
		return nil
	}
	out := new(TargetWindowsList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetWindowsList) DeepCopyInto(out *TargetWindowsList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetWindows, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
