// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerGcp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerGcp) DeepCopy() *GatewayProducerGcp {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerGcp)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerGcp) DeepCopyInto(out *GatewayProducerGcp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerGcpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerGcpList) DeepCopy() *GatewayProducerGcpList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerGcpList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerGcpList) DeepCopyInto(out *GatewayProducerGcpList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerGcp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
