// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SshCertIssuerParameters defines the desired state of the resource.
type SshCertIssuerParameters struct {
	// +optional
	ProviderType *string `json:"ProviderType,omitempty"`
	// Users allowed to fetch the certificate, e.g. root,ubuntu
	// +kubebuilder:validation:Required
	AllowedUsers string `json:"allowed_users"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Signed certificates with extensions, e.g. permit-port-forwarding
	// +optional
	Extensions *string `json:"extensions,omitempty"`
	// Externally provided username [true/false]
	// +optional
	ExternalUsername *string `json:"external_username,omitempty"`
	// Key-name of IdP claim to extract username from (for external-username=true)
	// +optional
	FixedUserClaimKeyname *string `json:"fixed_user_claim_keyname,omitempty"`
	// Host provider type [explicit/target]
	// +optional
	HostProvider *string `json:"host_provider,omitempty"`
	// SSH certificate issuer name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Signed certificates with principal, e.g. example_role1,example_role2
	// +optional
	Principals *string `json:"principals,omitempty"`
	// Use internal SSH Access
	// +optional
	SecureAccessUseInternalSshAccess *bool `json:"secure_access_use_internal_ssh_access,omitempty"`
	// Key to sign the certificate with
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	SignerKeyName string `json:"signer_key_name"`
	// Tags for the SSH cert issuer
	// +optional
	Tag *string `json:"tag,omitempty"`
	// A list of linked targets to be associated, Relevant only for Secure Remote Access for ssh cert issuer, ldap rotated secret and ldap dynamic secret, To specify multiple targets use argument multiple times
	// +optional
	Target *string `json:"target,omitempty"`
	// Certificate TTL in seconds
	// +kubebuilder:validation:Required
	Ttl int64 `json:"ttl"`
}

// SshCertIssuerObservation reflects the observed state from the upstream provider.
type SshCertIssuerObservation struct {
}

// SshCertIssuerSpec is the desired state of the resource.
type SshCertIssuerSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       SshCertIssuerParameters `json:"forProvider"`
}

// SshCertIssuerStatus reflects the observed state of the resource.
type SshCertIssuerStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SshCertIssuerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type SshCertIssuer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SshCertIssuerSpec   `json:"spec"`
	Status            SshCertIssuerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type SshCertIssuerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SshCertIssuer `json:"items"`
}
