// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *SshCertIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SshCertIssuer) DeepCopy() *SshCertIssuer {
	if in == nil {
		return nil
	}
	out := new(SshCertIssuer)
	in.DeepCopyInto(out)
	return out
}

func (in *SshCertIssuer) DeepCopyInto(out *SshCertIssuer) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *SshCertIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SshCertIssuerList) DeepCopy() *SshCertIssuerList {
	if in == nil {
		return nil
	}
	out := new(SshCertIssuerList)
	in.DeepCopyInto(out)
	return out
}

func (in *SshCertIssuerList) DeepCopyInto(out *SshCertIssuerList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SshCertIssuer, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
