// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretCustomParameters defines the desired state of the resource.
type DynamicSecretCustomParameters struct {
	// Admin credentials rotation interval in days
	// +optional
	AdminRotationIntervalDays *int64 `json:"admin_rotation_interval_days,omitempty"`
	// URL to call on create/sync
	// +kubebuilder:validation:Required
	CreateSyncUrl string `json:"create_sync_url"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Enable admin credentials rotation
	// +optional
	EnableAdminRotation *bool `json:"enable_admin_rotation,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Custom payload to send to the URL
	// +optional
	Payload *string `json:"payload,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// URL to call on revoke
	// +kubebuilder:validation:Required
	RevokeSyncUrl string `json:"revoke_sync_url"`
	// URL to call on rotate
	// +optional
	RotateSyncUrl *string `json:"rotate_sync_url,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Timeout in seconds for custom calls
	// +optional
	TimeoutSec *int64 `json:"timeout_sec,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretCustomObservation reflects the observed state from the upstream provider.
type DynamicSecretCustomObservation struct {
}

// DynamicSecretCustomSpec is the desired state of the resource.
type DynamicSecretCustomSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretCustomParameters `json:"forProvider"`
}

// DynamicSecretCustomStatus reflects the observed state of the resource.
type DynamicSecretCustomStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretCustomObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretCustom struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretCustomSpec   `json:"spec"`
	Status            DynamicSecretCustomStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretCustomList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretCustom `json:"items"`
}
