// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretOpenai) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretOpenai) DeepCopy() *DynamicSecretOpenai {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretOpenai)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretOpenai) DeepCopyInto(out *DynamicSecretOpenai) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretOpenaiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretOpenaiList) DeepCopy() *DynamicSecretOpenaiList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretOpenaiList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretOpenaiList) DeepCopyInto(out *DynamicSecretOpenaiList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretOpenai, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
