// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetLinkedParameters defines the desired state of the resource.
type TargetLinkedParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// Hosts for the linked target
	// +optional
	Hosts *string `json:"hosts,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Parent target name to link to
	// +optional
	ParentTargetName *string `json:"parent_target_name,omitempty"`
	// Specifies the hosts type, relevant only when working without parent target
	// +optional
	Type *string `json:"type,omitempty"`
}

// TargetLinkedObservation reflects the observed state from the upstream provider.
type TargetLinkedObservation struct {
}

// TargetLinkedSpec is the desired state of the resource.
type TargetLinkedSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetLinkedParameters `json:"forProvider"`
}

// TargetLinkedStatus reflects the observed state of the resource.
type TargetLinkedStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetLinkedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetLinked struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetLinkedSpec   `json:"spec"`
	Status            TargetLinkedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetLinkedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetLinked `json:"items"`
}
