// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GatewayProducerOracleParameters defines the desired state of the resource.
type GatewayProducerOracleParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// (Optional) DB server certificates
	// +optional
	DbServerCertificates *string `json:"db_server_certificates,omitempty"`
	// (Optional) Server name for certificate verification
	// +optional
	DbServerName *string `json:"db_server_name,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Oracle Host
	// +optional
	OracleHost *string `json:"oracle_host,omitempty"`
	// Oracle Password
	// +optional
	OraclePassword *string `json:"oracle_password,omitempty"`
	// Oracle Port
	// +optional
	OraclePort *string `json:"oracle_port,omitempty"`
	// Oracle Revocation statements
	// +optional
	OracleRevocationStatements *string `json:"oracle_revocation_statements,omitempty"`
	// Oracle Creation statements
	// +optional
	OracleScreationStatements *string `json:"oracle_screation_statements,omitempty"`
	// Oracle DB Name
	// +optional
	OracleServiceName *string `json:"oracle_service_name,omitempty"`
	// Oracle Username
	// +optional
	OracleUsername *string `json:"oracle_username,omitempty"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Add tags attached to this object
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// GatewayProducerOracleObservation reflects the observed state from the upstream provider.
type GatewayProducerOracleObservation struct {
}

// GatewayProducerOracleSpec is the desired state of the resource.
type GatewayProducerOracleSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       GatewayProducerOracleParameters `json:"forProvider"`
}

// GatewayProducerOracleStatus reflects the observed state of the resource.
type GatewayProducerOracleStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          GatewayProducerOracleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type GatewayProducerOracle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GatewayProducerOracleSpec   `json:"spec"`
	Status            GatewayProducerOracleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GatewayProducerOracleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayProducerOracle `json:"items"`
}
