// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodOidc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodOidc) DeepCopy() *AuthMethodOidc {
	if in == nil {
		return nil
	}
	out := new(AuthMethodOidc)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodOidc) DeepCopyInto(out *AuthMethodOidc) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodOidcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodOidcList) DeepCopy() *AuthMethodOidcList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodOidcList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodOidcList) DeepCopyInto(out *AuthMethodOidcList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodOidc, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
