// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RoleRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RoleRule) DeepCopy() *RoleRule {
	if in == nil {
		return nil
	}
	out := new(RoleRule)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleRule) DeepCopyInto(out *RoleRule) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RoleRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RoleRuleList) DeepCopy() *RoleRuleList {
	if in == nil {
		return nil
	}
	out := new(RoleRuleList)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleRuleList) DeepCopyInto(out *RoleRuleList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RoleRule, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
