// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetAwsParameters defines the desired state of the resource.
type TargetAwsParameters struct {
	// AWS secret access key
	// +kubebuilder:validation:Required
	AccessKey string `json:"access_key"`
	// AWS access key ID
	// +kubebuilder:validation:Required
	AccessKeyId string `json:"access_key_id"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// A unique auto-generated value used in your AWS account when configuring your AWS IAM role to securely delegate access to Akeyless. Relevant only when using GW cloud ID
	// +optional
	GenerateExternalId *bool `json:"generate_external_id,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// AWS region
	// +optional
	Region *string `json:"region,omitempty"`
	// AWS IAM role identifier that Gateway will assume in your AWS account, relevant only when using external ID
	// +optional
	RoleArn *string `json:"role_arn,omitempty"`
	// AWS session token (for temporary credentials)
	// +optional
	SessionToken *string `json:"session_token,omitempty"`
	// Use gateway cloud identity for authentication
	// +optional
	UseGwCloudIdentity *bool `json:"use_gw_cloud_identity,omitempty"`
}

// TargetAwsObservation reflects the observed state from the upstream provider.
type TargetAwsObservation struct {
}

// TargetAwsSpec is the desired state of the resource.
type TargetAwsSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetAwsParameters `json:"forProvider"`
}

// TargetAwsStatus reflects the observed state of the resource.
type TargetAwsStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetAwsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetAws struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetAwsSpec   `json:"spec"`
	Status            TargetAwsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetAwsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetAws `json:"items"`
}
