// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetZerossl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetZerossl) DeepCopy() *TargetZerossl {
	if in == nil {
		return nil
	}
	out := new(TargetZerossl)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetZerossl) DeepCopyInto(out *TargetZerossl) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetZerosslList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetZerosslList) DeepCopy() *TargetZerosslList {
	if in == nil {
		return nil
	}
	out := new(TargetZerosslList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetZerosslList) DeepCopyInto(out *TargetZerosslList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetZerossl, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
