// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretVenafiParameters defines the desired state of the resource.
type DynamicSecretVenafiParameters struct {
	// Admin credentials rotation interval (days)
	// +optional
	AdminRotationIntervalDays *int64 `json:"admin_rotation_interval_days,omitempty"`
	// Allow subdomains
	// +optional
	AllowSubdomains *bool `json:"allow_subdomains,omitempty"`
	// Allowed domains
	// +optional
	AllowedDomains *string `json:"allowed_domains,omitempty"`
	// Auto generated folder
	// +optional
	AutoGeneratedFolder *string `json:"auto_generated_folder,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Automatic admin credentials rotation
	// +optional
	EnableAdminRotation *bool `json:"enable_admin_rotation,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Root first in chain
	// +optional
	RootFirstInChain *bool `json:"root_first_in_chain,omitempty"`
	// Use Akeyless PKI issuer or Venafi issuer
	// +optional
	SignUsingAkeylessPki *bool `json:"sign_using_akeyless_pki,omitempty"`
	// Signer key name
	// +optional
	SignerKeyName *string `json:"signer_key_name,omitempty"`
	// Store private key in Akeyless
	// +optional
	StorePrivateKey *bool `json:"store_private_key,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
	// Venafi Access Token to use to access the TPP environment (Relevant when using TPP)
	// +optional
	VenafiAccessToken *string `json:"venafi_access_token,omitempty"`
	// Venafi API key
	// +optional
	VenafiApiKey *string `json:"venafi_api_key,omitempty"`
	// Venafi base URL
	// +optional
	VenafiBaseurl *string `json:"venafi_baseurl,omitempty"`
	// Venafi Client ID that was used when the access token was generated
	// +optional
	VenafiClientId *string `json:"venafi_client_id,omitempty"`
	// Venafi Refresh Token to use when the Access Token is expired (Relevant when using TPP)
	// +optional
	VenafiRefreshToken *string `json:"venafi_refresh_token,omitempty"`
	// Use Venafi TPP (instead of Cloud)
	// +optional
	VenafiUseTpp *bool `json:"venafi_use_tpp,omitempty"`
	// Venafi zone/policy folder
	// +optional
	VenafiZone *string `json:"venafi_zone,omitempty"`
}

// DynamicSecretVenafiObservation reflects the observed state from the upstream provider.
type DynamicSecretVenafiObservation struct {
}

// DynamicSecretVenafiSpec is the desired state of the resource.
type DynamicSecretVenafiSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretVenafiParameters `json:"forProvider"`
}

// DynamicSecretVenafiStatus reflects the observed state of the resource.
type DynamicSecretVenafiStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretVenafiObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretVenafi struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretVenafiSpec   `json:"spec"`
	Status            DynamicSecretVenafiStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretVenafiList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretVenafi `json:"items"`
}
