// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretVenafi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretVenafi) DeepCopy() *DynamicSecretVenafi {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretVenafi)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretVenafi) DeepCopyInto(out *DynamicSecretVenafi) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretVenafiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretVenafiList) DeepCopy() *DynamicSecretVenafiList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretVenafiList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretVenafiList) DeepCopyInto(out *DynamicSecretVenafiList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretVenafi, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
