// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodHuaweiParameters defines the desired state of the resource.
type AuthMethodHuaweiParameters struct {
	// Access expiration date in Unix timestamp (select 0 for access without expiry date)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// sts URL
	// +optional
	AuthUrl *string `json:"auth_url,omitempty"`
	// A list of domain IDs that the access is restricted to
	// +optional
	BoundDomainId *string `json:"bound_domain_id,omitempty"`
	// A list of domain names that the access is restricted to
	// +optional
	BoundDomainName *string `json:"bound_domain_name,omitempty"`
	// A CIDR whitelist with the IPs that the access is restricted to
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// A list of full tenant ids that the access is restricted to
	// +optional
	BoundTenantId *string `json:"bound_tenant_id,omitempty"`
	// A list of full tenant names that the access is restricted to
	// +optional
	BoundTenantName *string `json:"bound_tenant_name,omitempty"`
	// A list of full user ids that the access is restricted to
	// +optional
	BoundUserId *string `json:"bound_user_id,omitempty"`
	// A list of full user-name that the access is restricted to
	// +optional
	BoundUserName *string `json:"bound_user_name,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	// +optional
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// if true: enforce role-association must include sub claims
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// A CIDR whitelist with the GW IPs that the access is restricted to
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// Jwt TTL
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
}

// AuthMethodHuaweiObservation reflects the observed state from the upstream provider.
type AuthMethodHuaweiObservation struct {
}

// AuthMethodHuaweiSpec is the desired state of the resource.
type AuthMethodHuaweiSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodHuaweiParameters `json:"forProvider"`
}

// AuthMethodHuaweiStatus reflects the observed state of the resource.
type AuthMethodHuaweiStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodHuaweiObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodHuawei struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodHuaweiSpec   `json:"spec"`
	Status            AuthMethodHuaweiStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodHuaweiList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodHuawei `json:"items"`
}
