// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretArtifactoryParameters defines the desired state of the resource.
type DynamicSecretArtifactoryParameters struct {
	// Artifactory admin username
	// +optional
	ArtifactoryAdminName *string `json:"artifactory_admin_name,omitempty"`
	// Artifactory admin password
	// +optional
	ArtifactoryAdminPwd *string `json:"artifactory_admin_pwd,omitempty"`
	// Artifactory token audience
	// +kubebuilder:validation:Required
	ArtifactoryTokenAudience string `json:"artifactory_token_audience"`
	// Artifactory token scope
	// +kubebuilder:validation:Required
	ArtifactoryTokenScope string `json:"artifactory_token_scope"`
	// Artifactory base URL
	// +optional
	BaseUrl *string `json:"base_url,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretArtifactoryObservation reflects the observed state from the upstream provider.
type DynamicSecretArtifactoryObservation struct {
}

// DynamicSecretArtifactorySpec is the desired state of the resource.
type DynamicSecretArtifactorySpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretArtifactoryParameters `json:"forProvider"`
}

// DynamicSecretArtifactoryStatus reflects the observed state of the resource.
type DynamicSecretArtifactoryStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretArtifactoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretArtifactory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretArtifactorySpec   `json:"spec"`
	Status            DynamicSecretArtifactoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretArtifactoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretArtifactory `json:"items"`
}
