// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetSplunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSplunk) DeepCopy() *TargetSplunk {
	if in == nil {
		return nil
	}
	out := new(TargetSplunk)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSplunk) DeepCopyInto(out *TargetSplunk) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetSplunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetSplunkList) DeepCopy() *TargetSplunkList {
	if in == nil {
		return nil
	}
	out := new(TargetSplunkList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSplunkList) DeepCopyInto(out *TargetSplunkList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetSplunk, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
