// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodAzureAdParameters defines the desired state of the resource.
type AuthMethodAzureAdParameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Azure AD audience (application ID)
	// +optional
	Audience *string `json:"audience,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// Azure AD group IDs to restrict access
	// +optional
	BoundGroupId *string `json:"bound_group_id,omitempty"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// Azure resource providers to restrict access
	// +optional
	BoundProviders *string `json:"bound_providers,omitempty"`
	// Azure resource IDs to restrict access
	// +optional
	BoundResourceId *string `json:"bound_resource_id,omitempty"`
	// Azure resource names to restrict access
	// +optional
	BoundResourceNames *string `json:"bound_resource_names,omitempty"`
	// Azure resource types to restrict access
	// +optional
	BoundResourceTypes *string `json:"bound_resource_types,omitempty"`
	// Azure resource group IDs to restrict access
	// +optional
	BoundRgId *string `json:"bound_rg_id,omitempty"`
	// Service principal IDs to restrict access
	// +optional
	BoundSpid *string `json:"bound_spid,omitempty"`
	// Azure subscription IDs to restrict access
	// +optional
	BoundSubId *string `json:"bound_sub_id,omitempty"`
	// Azure tenant ID to restrict access
	// +kubebuilder:validation:Required
	BoundTenantId string `json:"bound_tenant_id"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// Azure AD issuer URL
	// +optional
	Issuer *string `json:"issuer,omitempty"`
	// JWKS URI for token verification
	// +optional
	JwksUri *string `json:"jwks_uri,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
	// A unique identifier (ID) value which is a "sub claim" name that contains details uniquely identifying that resource. This "sub claim" is used to distinguish between different identities.
	// +optional
	UniqueIdentifier *string `json:"unique_identifier,omitempty"`
}

// AuthMethodAzureAdObservation reflects the observed state from the upstream provider.
type AuthMethodAzureAdObservation struct {
}

// AuthMethodAzureAdSpec is the desired state of the resource.
type AuthMethodAzureAdSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodAzureAdParameters `json:"forProvider"`
}

// AuthMethodAzureAdStatus reflects the observed state of the resource.
type AuthMethodAzureAdStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodAzureAdObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodAzureAd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodAzureAdSpec   `json:"spec"`
	Status            AuthMethodAzureAdStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodAzureAdList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodAzureAd `json:"items"`
}
