// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayAllowedAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayAllowedAccess) DeepCopy() *GatewayAllowedAccess {
	if in == nil {
		return nil
	}
	out := new(GatewayAllowedAccess)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayAllowedAccess) DeepCopyInto(out *GatewayAllowedAccess) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayAllowedAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayAllowedAccessList) DeepCopy() *GatewayAllowedAccessList {
	if in == nil {
		return nil
	}
	out := new(GatewayAllowedAccessList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayAllowedAccessList) DeepCopyInto(out *GatewayAllowedAccessList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayAllowedAccess, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
