// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetRabbitmq) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetRabbitmq) DeepCopy() *TargetRabbitmq {
	if in == nil {
		return nil
	}
	out := new(TargetRabbitmq)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetRabbitmq) DeepCopyInto(out *TargetRabbitmq) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetRabbitmqList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetRabbitmqList) DeepCopy() *TargetRabbitmqList {
	if in == nil {
		return nil
	}
	out := new(TargetRabbitmqList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetRabbitmqList) DeepCopyInto(out *TargetRabbitmqList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetRabbitmq, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
