// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayK8sAuthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayK8sAuthConfig) DeepCopy() *GatewayK8sAuthConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayK8sAuthConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayK8sAuthConfig) DeepCopyInto(out *GatewayK8sAuthConfig) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayK8sAuthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayK8sAuthConfigList) DeepCopy() *GatewayK8sAuthConfigList {
	if in == nil {
		return nil
	}
	out := new(GatewayK8sAuthConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayK8sAuthConfigList) DeepCopyInto(out *GatewayK8sAuthConfigList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayK8sAuthConfig, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
