// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EsmParameters defines the desired state of the resource.
type EsmParameters struct {
	// Use this option if the external secret value is a base64 encoded binary
	// +optional
	BinaryValue *bool `json:"binary_value,omitempty"`
	// Description of the external secret
	// +optional
	Description *string `json:"description,omitempty"`
	// Name of the External Secrets Manager item
	// +kubebuilder:validation:Required
	EsmName string `json:"esm_name"`
	// Name for the new external secret
	// +kubebuilder:validation:Required
	SecretName string `json:"secret_name"`
	// Tags for the external secret
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Value of the external secret item, either text or base64 encoded binary
	// +kubebuilder:validation:Required
	Value string `json:"value"`
}

// EsmObservation reflects the observed state from the upstream provider.
type EsmObservation struct {
}

// EsmSpec is the desired state of the resource.
type EsmSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       EsmParameters `json:"forProvider"`
}

// EsmStatus reflects the observed state of the resource.
type EsmStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          EsmObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Esm struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EsmSpec   `json:"spec"`
	Status            EsmStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type EsmList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Esm `json:"items"`
}
