// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *EventForwarderTeams) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderTeams) DeepCopy() *EventForwarderTeams {
	if in == nil {
		return nil
	}
	out := new(EventForwarderTeams)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderTeams) DeepCopyInto(out *EventForwarderTeams) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *EventForwarderTeamsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EventForwarderTeamsList) DeepCopy() *EventForwarderTeamsList {
	if in == nil {
		return nil
	}
	out := new(EventForwarderTeamsList)
	in.DeepCopyInto(out)
	return out
}

func (in *EventForwarderTeamsList) DeepCopyInto(out *EventForwarderTeamsList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EventForwarderTeams, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
