// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayLogForwardingAzureAnalytics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingAzureAnalytics) DeepCopy() *GatewayLogForwardingAzureAnalytics {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingAzureAnalytics)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingAzureAnalytics) DeepCopyInto(out *GatewayLogForwardingAzureAnalytics) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayLogForwardingAzureAnalyticsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayLogForwardingAzureAnalyticsList) DeepCopy() *GatewayLogForwardingAzureAnalyticsList {
	if in == nil {
		return nil
	}
	out := new(GatewayLogForwardingAzureAnalyticsList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayLogForwardingAzureAnalyticsList) DeepCopyInto(out *GatewayLogForwardingAzureAnalyticsList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayLogForwardingAzureAnalytics, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
