// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PolicyParameters defines the desired state of the resource.
type PolicyParameters struct {
	// Specify allowed key algorithms (e.g., [RSA2048,AES128GCM])
	// +optional
	AllowedAlgorithms *string `json:"allowed_algorithms,omitempty"`
	// Specify allowed protection key names. To enforce using the account's default protection key, use 'default-account-key'
	// +optional
	AllowedKeyNames *string `json:"allowed_key_names,omitempty"`
	// Specify allowed key protection types (dfc, classic-key)
	// +optional
	AllowedKeyTypes *string `json:"allowed_key_types,omitempty"`
	// Set the maximum rotation interval for automatic key rotation.
	// +optional
	MaxRotationIntervalDays *int64 `json:"max_rotation_interval_days,omitempty"`
	// The object types this policy will apply to (items, targets). If not provided, defaults to [items, targets].
	// +optional
	ObjectTypes *string `json:"object_types,omitempty"`
	// The path the policy refers to
	// +kubebuilder:validation:Required
	Path string `json:"path"`
}

// PolicyObservation reflects the observed state from the upstream provider.
type PolicyObservation struct {
}

// PolicySpec is the desired state of the resource.
type PolicySpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       PolicyParameters `json:"forProvider"`
}

// PolicyStatus reflects the observed state of the resource.
type PolicyStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PolicySpec   `json:"spec"`
	Status            PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}
