// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EventForwarderEmailParameters defines the desired state of the resource.
type EventForwarderEmailParameters struct {
	// Auth Method Event sources
	// +optional
	AuthMethodsEventSourceLocations *string `json:"auth_methods_event_source_locations,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// A comma seperated list of email addresses to send event to
	// +optional
	EmailTo *string `json:"email_to,omitempty"`
	// List of event types to notify about [request-access, certificate-pending-expiration, certificate-expired, certificate-provisioning-success, certificate-provisioning-failure, auth-method-pending-expiration, auth-method-expired, next-automatic-rotation, rotated-secret-success, rotated-secret-failure, dynamic-secret-failure, multi-auth-failure, uid-rotation-failure, apply-justification, email-auth-method-approved, usage, rotation-usage, gateway-inactive, static-secret-updated, rate-limiting, usage-report, secret-sync]
	// +optional
	EventTypes *string `json:"event_types,omitempty"`
	// Rate of periodic runner repetition in hours
	// +optional
	Every *string `json:"every,omitempty"`
	// Event sources
	// +kubebuilder:validation:Required
	GatewaysEventSourceLocations string `json:"gateways_event_source_locations"`
	// Set this option to include event errors details [true/false]
	// +optional
	IncludeError *string `json:"include_error,omitempty"`
	// Items Event sources
	// +optional
	ItemsEventSourceLocations *string `json:"items_event_source_locations,omitempty"`
	// The name of a key that used to encrypt the EventForwarder secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// EventForwarder name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Override Akeyless default URL with your Gateway url (port 18888)
	// +optional
	OverrideUrl *string `json:"override_url,omitempty"`
	// +kubebuilder:validation:Required
	RunnerType string `json:"runner_type"`
	// Targets Event sources
	// +optional
	TargetsEventSourceLocations *string `json:"targets_event_source_locations,omitempty"`
}

// EventForwarderEmailObservation reflects the observed state from the upstream provider.
type EventForwarderEmailObservation struct {
}

// EventForwarderEmailSpec is the desired state of the resource.
type EventForwarderEmailSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       EventForwarderEmailParameters `json:"forProvider"`
}

// EventForwarderEmailStatus reflects the observed state of the resource.
type EventForwarderEmailStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          EventForwarderEmailObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type EventForwarderEmail struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EventForwarderEmailSpec   `json:"spec"`
	Status            EventForwarderEmailStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type EventForwarderEmailList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EventForwarderEmail `json:"items"`
}
