// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *GatewayProducerHanadb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerHanadb) DeepCopy() *GatewayProducerHanadb {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerHanadb)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerHanadb) DeepCopyInto(out *GatewayProducerHanadb) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *GatewayProducerHanadbList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayProducerHanadbList) DeepCopy() *GatewayProducerHanadbList {
	if in == nil {
		return nil
	}
	out := new(GatewayProducerHanadbList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayProducerHanadbList) DeepCopyInto(out *GatewayProducerHanadbList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]GatewayProducerHanadb, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
