// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *RotatedSecretRedshift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretRedshift) DeepCopy() *RotatedSecretRedshift {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretRedshift)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretRedshift) DeepCopyInto(out *RotatedSecretRedshift) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *RotatedSecretRedshiftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RotatedSecretRedshiftList) DeepCopy() *RotatedSecretRedshiftList {
	if in == nil {
		return nil
	}
	out := new(RotatedSecretRedshiftList)
	in.DeepCopyInto(out)
	return out
}

func (in *RotatedSecretRedshiftList) DeepCopyInto(out *RotatedSecretRedshiftList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RotatedSecretRedshift, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
