// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthMethodAwsIamParameters defines the desired state of the resource.
type AuthMethodAwsIamParameters struct {
	// Access expiration in Unix time (0 = no expiry)
	// +optional
	AccessExpires *int64 `json:"access_expires,omitempty"`
	// limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]
	// +optional
	AllowedClientType *string `json:"allowed_client_type,omitempty"`
	// Subclaims to include in audit logs, e.g "--audit-logs-claims email --audit-logs-claims username"
	// +optional
	AuditLogsClaims *string `json:"audit_logs_claims,omitempty"`
	// Full ARNs to restrict access
	// +optional
	BoundArn *string `json:"bound_arn,omitempty"`
	// AWS account IDs to restrict access
	// +kubebuilder:validation:Required
	BoundAwsAccountId string `json:"bound_aws_account_id"`
	// CIDR whitelist for access
	// +optional
	BoundIps *string `json:"bound_ips,omitempty"`
	// AWS resource IDs to restrict access
	// +optional
	BoundResourceId *string `json:"bound_resource_id,omitempty"`
	// AWS role IDs to restrict access
	// +optional
	BoundRoleId *string `json:"bound_role_id,omitempty"`
	// AWS role names to restrict access
	// +optional
	BoundRoleName *string `json:"bound_role_name,omitempty"`
	// AWS user IDs to restrict access
	// +optional
	BoundUserId *string `json:"bound_user_id,omitempty"`
	// AWS user names to restrict access
	// +optional
	BoundUserName *string `json:"bound_user_name,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Auth Method description
	// +optional
	Description *string `json:"description,omitempty"`
	// How many days before the expiration of the auth method would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Force sub-claims enforcement
	// +optional
	ForceSubClaims *bool `json:"force_sub_claims,omitempty"`
	// Gateway CIDR whitelist
	// +optional
	GwBoundIps *string `json:"gw_bound_ips,omitempty"`
	// JWT TTL in seconds
	// +optional
	JwtTtl *int64 `json:"jwt_ttl,omitempty"`
	// Auth Method name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]
	// +optional
	ProductType *string `json:"product_type,omitempty"`
	// STS endpoint URL (default: https://sts.amazonaws.com)
	// +optional
	StsUrl *string `json:"sts_url,omitempty"`
	// A unique identifier (ID) value which is a "sub claim" name that contains details uniquely identifying that resource. This "sub claim" is used to distinguish between different identities.
	// +optional
	UniqueIdentifier *string `json:"unique_identifier,omitempty"`
}

// AuthMethodAwsIamObservation reflects the observed state from the upstream provider.
type AuthMethodAwsIamObservation struct {
}

// AuthMethodAwsIamSpec is the desired state of the resource.
type AuthMethodAwsIamSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AuthMethodAwsIamParameters `json:"forProvider"`
}

// AuthMethodAwsIamStatus reflects the observed state of the resource.
type AuthMethodAwsIamStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AuthMethodAwsIamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type AuthMethodAwsIam struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthMethodAwsIamSpec   `json:"spec"`
	Status            AuthMethodAwsIamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type AuthMethodAwsIamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethodAwsIam `json:"items"`
}
