// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *AuthMethodAwsIam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodAwsIam) DeepCopy() *AuthMethodAwsIam {
	if in == nil {
		return nil
	}
	out := new(AuthMethodAwsIam)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodAwsIam) DeepCopyInto(out *AuthMethodAwsIam) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *AuthMethodAwsIamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthMethodAwsIamList) DeepCopy() *AuthMethodAwsIamList {
	if in == nil {
		return nil
	}
	out := new(AuthMethodAwsIamList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthMethodAwsIamList) DeepCopyInto(out *AuthMethodAwsIamList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AuthMethodAwsIam, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
