// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetWebParameters defines the desired state of the resource.
type TargetWebParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Web target URL
	// +optional
	Url *string `json:"url,omitempty"`
}

// TargetWebObservation reflects the observed state from the upstream provider.
type TargetWebObservation struct {
}

// TargetWebSpec is the desired state of the resource.
type TargetWebSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetWebParameters `json:"forProvider"`
}

// TargetWebStatus reflects the observed state of the resource.
type TargetWebStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetWebObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetWeb struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetWebSpec   `json:"spec"`
	Status            TargetWebStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetWebList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetWeb `json:"items"`
}
