// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetWeb) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetWeb) DeepCopy() *TargetWeb {
	if in == nil {
		return nil
	}
	out := new(TargetWeb)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetWeb) DeepCopyInto(out *TargetWeb) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetWebList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetWebList) DeepCopy() *TargetWebList {
	if in == nil {
		return nil
	}
	out := new(TargetWebList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetWebList) DeepCopyInto(out *TargetWebList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetWeb, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
