// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KmipEnvironmentParameters defines the desired state of the resource.
type KmipEnvironmentParameters struct {
	// Server certificate TTL in days
	// +optional
	CertificateTtl *int64 `json:"certificate_ttl,omitempty"`
	// How many days before the expiration of the certificate would you like to be notified.
	// +optional
	ExpirationEventIn *string `json:"expiration_event_in,omitempty"`
	// Hostname
	// +kubebuilder:validation:Required
	Hostname string `json:"hostname"`
	// Root path of KMIP Resources
	// +kubebuilder:validation:Required
	Root string `json:"root"`
}

// KmipEnvironmentObservation reflects the observed state from the upstream provider.
type KmipEnvironmentObservation struct {
}

// KmipEnvironmentSpec is the desired state of the resource.
type KmipEnvironmentSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       KmipEnvironmentParameters `json:"forProvider"`
}

// KmipEnvironmentStatus reflects the observed state of the resource.
type KmipEnvironmentStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          KmipEnvironmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type KmipEnvironment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KmipEnvironmentSpec   `json:"spec"`
	Status            KmipEnvironmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type KmipEnvironmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KmipEnvironment `json:"items"`
}
