// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetGkeParameters defines the desired state of the resource.
type TargetGkeParameters struct {
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Target description
	// +optional
	Description *string `json:"description,omitempty"`
	// GCP service account key JSON (base64)
	// +optional
	GkeAccountKey *string `json:"gke_account_key,omitempty"`
	// GKE cluster CA certificate (PEM)
	// +optional
	GkeClusterCert *string `json:"gke_cluster_cert,omitempty"`
	// GKE cluster API server URL
	// +optional
	GkeClusterEndpoint *string `json:"gke_cluster_endpoint,omitempty"`
	// GKE cluster name
	// +optional
	GkeClusterName *string `json:"gke_cluster_name,omitempty"`
	// GCP service account email
	// +optional
	GkeServiceAccountEmail *string `json:"gke_service_account_email,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	// +optional
	Key *string `json:"key,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Target name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Use gateway cloud identity for authentication
	// +optional
	UseGwCloudIdentity *bool `json:"use_gw_cloud_identity,omitempty"`
}

// TargetGkeObservation reflects the observed state from the upstream provider.
type TargetGkeObservation struct {
}

// TargetGkeSpec is the desired state of the resource.
type TargetGkeSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       TargetGkeParameters `json:"forProvider"`
}

// TargetGkeStatus reflects the observed state of the resource.
type TargetGkeStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          TargetGkeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type TargetGke struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TargetGkeSpec   `json:"spec"`
	Status            TargetGkeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type TargetGkeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TargetGke `json:"items"`
}
