// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *TargetGke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGke) DeepCopy() *TargetGke {
	if in == nil {
		return nil
	}
	out := new(TargetGke)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGke) DeepCopyInto(out *TargetGke) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *TargetGkeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TargetGkeList) DeepCopy() *TargetGkeList {
	if in == nil {
		return nil
	}
	out := new(TargetGkeList)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetGkeList) DeepCopyInto(out *TargetGkeList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TargetGke, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
