// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FolderParameters defines the desired state of the resource.
type FolderParameters struct {
	// Folder accessibility: regular or personal
	// +optional
	Accessibility *string `json:"accessibility,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the folder
	// +optional
	Description *string `json:"description,omitempty"`
	// Folder name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Tags for the folder
	// +optional
	Tags *string `json:"tags,omitempty"`
	// +optional
	Type *string `json:"type,omitempty"`
}

// FolderObservation reflects the observed state from the upstream provider.
type FolderObservation struct {
}

// FolderSpec is the desired state of the resource.
type FolderSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       FolderParameters `json:"forProvider"`
}

// FolderStatus reflects the observed state of the resource.
type FolderStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          FolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type Folder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FolderSpec   `json:"spec"`
	Status            FolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type FolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Folder `json:"items"`
}
