// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *OidcApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OidcApp) DeepCopy() *OidcApp {
	if in == nil {
		return nil
	}
	out := new(OidcApp)
	in.DeepCopyInto(out)
	return out
}

func (in *OidcApp) DeepCopyInto(out *OidcApp) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *OidcAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OidcAppList) DeepCopy() *OidcAppList {
	if in == nil {
		return nil
	}
	out := new(OidcAppList)
	in.DeepCopyInto(out)
	return out
}

func (in *OidcAppList) DeepCopyInto(out *OidcAppList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]OidcApp, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
