// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretPostgresqlParameters defines the desired state of the resource.
type DynamicSecretPostgresqlParameters struct {
	// PostgreSQL creation statements
	// +optional
	CreationStatements *string `json:"creation_statements,omitempty"`
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
	// +optional
	InputRule *string `json:"input_rule,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	// +optional
	OutputRule *string `json:"output_rule,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// PostgreSQL DB Name
	// +optional
	PostgresqlDbName *string `json:"postgresql_db_name,omitempty"`
	// PostgreSQL host
	// +optional
	PostgresqlHost *string `json:"postgresql_host,omitempty"`
	// PostgreSQL admin password
	// +optional
	PostgresqlPassword *string `json:"postgresql_password,omitempty"`
	// PostgreSQL port (default: 5432)
	// +optional
	PostgresqlPort *string `json:"postgresql_port,omitempty"`
	// PostgreSQL admin username
	// +optional
	PostgresqlUsername *string `json:"postgresql_username,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKey *string `json:"producer_encryption_key,omitempty"`
	// PostgreSQL Revocation statements
	// +optional
	RevocationStatement *string `json:"revocation_statement,omitempty"`
	// The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds
	// +optional
	SecureAccessDelay *int64 `json:"secure_access_delay,omitempty"`
	// Enable SSL connection
	// +optional
	Ssl *bool `json:"ssl,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	// +optional
	UseCapitalLetters *string `json:"use_capital_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	// +optional
	UseLowerLetters *string `json:"use_lower_letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	// +optional
	UseNumbers *string `json:"use_numbers,omitempty"`
	// +optional
	UseSpecialCharacters *string `json:"use_special_characters,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretPostgresqlObservation reflects the observed state from the upstream provider.
type DynamicSecretPostgresqlObservation struct {
}

// DynamicSecretPostgresqlSpec is the desired state of the resource.
type DynamicSecretPostgresqlSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DynamicSecretPostgresqlParameters `json:"forProvider"`
}

// DynamicSecretPostgresqlStatus reflects the observed state of the resource.
type DynamicSecretPostgresqlStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DynamicSecretPostgresqlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretPostgresql struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSecretPostgresqlSpec   `json:"spec"`
	Status            DynamicSecretPostgresqlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretPostgresqlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSecretPostgresql `json:"items"`
}
