// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretDockerhub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretDockerhub) DeepCopy() *DynamicSecretDockerhub {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretDockerhub)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretDockerhub) DeepCopyInto(out *DynamicSecretDockerhub) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretDockerhubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretDockerhubList) DeepCopy() *DynamicSecretDockerhubList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretDockerhubList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretDockerhubList) DeepCopyInto(out *DynamicSecretDockerhubList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretDockerhub, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
